// GENERATED CODE — DO NOT EDIT
import 'package:lsp_server/lsp_server.dart';
import 'models.dart';

const components = <DaisyuiComponent>[
DaisyuiComponent(label: 'stats', detail: 'Container of multiple stat items', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'stat', detail: 'A block to display stat data about a topic', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'stat-title', detail: 'Title part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'stat-value', detail: 'Value part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'stat-desc', detail: 'Description part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'stat-figure', detail: 'Figure part for icon, etc', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'stat-actions', detail: 'Actions part for button, etc', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'stats-horizontal', detail: 'Makes stats horizontal (default)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'stats-vertical', detail: 'Makes stats vertical', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'select', detail: 'For <select> element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'select-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'select-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'select-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'select-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'select-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'select-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'select-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'select-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'select-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'select-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'select-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'select-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'select-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'select-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'drawer', detail: 'The wrapper for sidebar and content', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'drawer-toggle', detail: 'The hidden checkbox that controls the state of drawer', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'drawer-content', detail: 'Content part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'drawer-side', detail: 'Sidebar part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'drawer-overlay', detail: 'Label that covers the page when drawer is open', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'drawer-end', detail: 'puts drawer to the other side', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'drawer-open', detail: 'Forces the drawer to be open', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'progress', detail: 'For <progress> tag', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'progress-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'progress-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'progress-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'progress-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'progress-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'progress-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'progress-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'progress-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'fieldset', detail: 'for the fieldset container', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'label', detail: 'label for inputs', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'fieldset-legend', detail: 'for the title of the fieldset', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'alert', detail: 'Container element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'alert-outline', detail: 'outline style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'alert-dash', detail: 'dash outline style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'alert-soft', detail: 'soft style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'alert-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'alert-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'alert-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'alert-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'alert-vertical', detail: 'Vertical layout, good for mobile', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'alert-horizontal', detail: 'Horizontal layout, good for desktop', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'divider', detail: 'A divider line between two elements', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'divider-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'divider-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'divider-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'divider-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'divider-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'divider-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'divider-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'divider-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'divider-vertical', detail: 'Divide vertical elements (on top of each other)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'divider-horizontal', detail: 'Divide horizontal elements (next to each other)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'divider-start', detail: 'Pushes the divider text to the start', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'divider-end', detail: 'Pushes the divider text to the end', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'hero', detail: 'Hero container', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'hero-content', detail: 'content part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'hero-overlay', detail: 'Overlay that covers the background image', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'link', detail: 'Adds underline', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'link-hover', detail: 'Only shows underline on hover', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'link-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'link-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'link-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'link-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'link-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'link-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'link-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'link-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'kbd', detail: 'Do show a keyboard key or a shortcut key', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'kbd-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'kbd-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'kbd-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'kbd-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'kbd-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'mockup-code', detail: 'Code terminal mockup', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'loading', detail: 'Loading element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'loading-spinner', detail: 'spinner animation', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'loading-dots', detail: 'dots animation', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'loading-ring', detail: 'ring animation', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'loading-ball', detail: 'ball animation', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'loading-bars', detail: 'bars animation', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'loading-infinity', detail: 'infinity animation', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'loading-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'loading-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'loading-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'loading-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'loading-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'skeleton', detail: 'A placeholder div with loading animation', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'swap', detail: 'Swap container', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'swap-on', detail: 'The child element that should be visible when checkbox is checked or when swap is active', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'swap-off', detail: 'The child element that should be visible when checkbox is not checked or when swap is not active', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'swap-indeterminate', detail: 'The child element that should be visible when checkbox is indeterminate', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'swap-active', detail: 'Activates the swap (no need for checkbox)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'swap-rotate', detail: 'Adds rotate effect to swap', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'swap-flip', detail: 'Adds flip effect to swap', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'badge', detail: 'Container element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'badge-outline', detail: 'outline style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'badge-dash', detail: 'dash outline style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'badge-soft', detail: 'soft style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'badge-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'badge-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'badge-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'badge-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'badge-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'badge-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'badge-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'badge-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'badge-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'badge-xs', detail: 'extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'badge-sm', detail: 'small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'badge-md', detail: 'medium size (default)', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'badge-lg', detail: 'large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'badge-xl', detail: 'extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'radio', detail: 'For radio input', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'radio-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'radio-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'radio-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'radio-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'radio-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'radio-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'radio-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'radio-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'radio-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'radio-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'radio-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'radio-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'radio-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'navbar', detail: 'Navigation bar', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'navbar-start', detail: 'For the div inside navbar, to fill 50% of width', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'navbar-center', detail: 'For the div inside navbar, to be at center horizontally', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'navbar-end', detail: 'For the div inside navbar, to fill second 50% of width', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'collapse', detail: 'Collapse', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'collapse-title', detail: 'Title part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'collapse-content', detail: 'Content part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'collapse-arrow', detail: 'Adds arrow icon', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'collapse-plus', detail: 'Adds plus/minus icon', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'collapse-open', detail: 'Force open', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'collapse-close', detail: 'Force close', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'textarea', detail: 'For <textarea> element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'textarea-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'textarea-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'textarea-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'textarea-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'textarea-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'textarea-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'textarea-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'textarea-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'textarea-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'textarea-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'textarea-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'textarea-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'textarea-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'textarea-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'btn', detail: 'Button', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'btn-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'btn-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'btn-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'btn-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'btn-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'btn-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'btn-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'btn-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'btn-outline', detail: 'outline style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'btn-dash', detail: 'dash style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'btn-soft', detail: 'soft style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'btn-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'btn-link', detail: 'looks like a link', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'btn-active', detail: 'looks active', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'btn-disabled', detail: 'looks disabled', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'btn-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'btn-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'btn-md', detail: 'Medium size (default)', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'btn-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'btn-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'btn-wide', detail: 'more horizontal padding', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'btn-block', detail: 'Full width', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'btn-square', detail: '1:1 ratio', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'btn-circle', detail: '1:1 ratio with rounded corners', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'chat', detail: 'Container for one line of conversation and its data', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'chat-image', detail: 'Author image', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'chat-header', detail: 'Text above the chat bubble', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'chat-footer', detail: 'Text below the chat bubble', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'chat-bubble', detail: 'Chat bubble', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'chat-start', detail: 'Aligns chat to start horizontally (required)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'chat-end', detail: 'Aligns chat to end horizontally (required)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'chat-bubble-neutral', detail: 'neutral color for chat-bubble', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'chat-bubble-primary', detail: 'primary color for chat-bubble', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'chat-bubble-secondary', detail: 'secondary color for chat-bubble', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'chat-bubble-accent', detail: 'accent color for chat-bubble', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'chat-bubble-info', detail: 'info color for chat-bubble', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'chat-bubble-success', detail: 'success color for chat-bubble', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'chat-bubble-warning', detail: 'warning color for chat-bubble', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'chat-bubble-error', detail: 'error color for chat-bubble', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'tabs', detail: 'Container of multiple tab items', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'tab', detail: 'A single tab button (can be button, link, div, radio input, etc)', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'tab-content', detail: 'Tab content that comes immediately after a tab', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'tabs-box', detail: 'box style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'tabs-border', detail: 'bottom border style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'tabs-lift', detail: 'lift style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'tab-active', detail: 'Makes a single tab look active', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tab-disabled', detail: 'Makes a single tab look disabled', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tabs-top', detail: 'Puts tab buttons on top of the tab-content (default)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tabs-bottom', detail: 'Puts tabs on under the tab-content', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tabs-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'tabs-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'tabs-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'tabs-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'tabs-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'stack', detail: 'Puts the children elements on top of each other', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'stack-top', detail: 'Aligns the children elements to the top', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'stack-bottom', detail: 'Aligns the children elements to the bottom', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'stack-start', detail: 'Aligns the children elements to the start (horizontally)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'stack-end', detail: 'Aligns the children elements to the end (horizontally)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'join', detail: 'For grouping multiple items', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'join-item', detail: 'Item inside join. Can be a button, input, etc.', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'join-vertical', detail: 'Show items vertically', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'join-horizontal', detail: 'Show items horizontally', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'range', detail: 'For <input type="range"> tag', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'range-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'range-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'range-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'range-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'range-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'range-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'range-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'range-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'range-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'range-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'range-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'range-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'range-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'checkbox', detail: 'Checkbox', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'checkbox-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'checkbox-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'checkbox-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'checkbox-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'checkbox-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'checkbox-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'checkbox-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'checkbox-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'checkbox-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'checkbox-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'checkbox-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'checkbox-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'checkbox-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'radial-progress', detail: 'Shows a radial progress', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'toast', detail: 'Container element that sticks to the corner of page', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'toast-start', detail: 'align horizontally to the left', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'toast-center', detail: 'align horizontally to the center', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'toast-end', detail: 'align horizontally to the right', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'toast-top', detail: 'align vertically to top', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'toast-middle', detail: 'align vertically to middle', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'toast-bottom', detail: 'align vertically to bottom', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'steps', detail: 'Container of multiple step nodes', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'step', detail: 'A single step node', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'step-icon', detail: 'For custom icon inside step', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'step-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'step-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'step-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'step-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'step-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'step-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'step-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'step-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'steps-vertical', detail: 'Makes steps vertical (default)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'steps-horizontal', detail: 'Makes steps horizontal', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'cally', detail: 'for Cally web component', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'pika-single', detail: 'for the input field that opens Pikaday calendar', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'react-day-picker', detail: 'for the DayPicker component', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'toggle', detail: 'For <input type="checkbox">', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'toggle-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'toggle-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'toggle-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'toggle-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'toggle-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'toggle-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'toggle-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'toggle-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'toggle-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'toggle-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'toggle-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'toggle-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'toggle-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'join', detail: 'For grouping multiple items', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'join-item', detail: 'Item inside join. Can be a button, input, etc.', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'join-vertical', detail: 'Show items vertically', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'join-horizontal', detail: 'Show items horizontally', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'mockup-phone', detail: 'Phone mockup', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'mockup-phone-camera', detail: 'Camera part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'mockup-phone-display', detail: 'Display part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'mockup-window', detail: 'OS window mockup', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'carousel', detail: 'Carousel container', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'carousel-item', detail: 'Carousel item', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'carousel-start', detail: 'Snap elements to start', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'carousel-center', detail: 'Snap elements to center', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'carousel-end', detail: 'Snap elements to end', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'carousel-horizontal', detail: 'Horizontal layout (default)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'carousel-vertical', detail: 'Vertical layout', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'list', detail: 'A vertical flex layout to include list rows', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'list-row', detail: 'The item inside list. A horizontal grid layout to include data', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'list-col-wrap', detail: 'For one of direct children of list-row to push it to the next line', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'list-col-grow', detail: 'For one of direct children of list-row to make it fill the remaining space', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tooltip', detail: 'Container element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'tooltip-content', detail: 'Optional. Setting a div as the content of the tooltip instead of the `data-tip` text', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'tooltip-top', detail: 'Put tooltip on top', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tooltip-bottom', detail: 'Put tooltip on bottom', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tooltip-left', detail: 'Put tooltip on left', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tooltip-right', detail: 'Put tooltip on right', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tooltip-open', detail: 'Force open tooltip', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'tooltip-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'tooltip-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'tooltip-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'tooltip-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'tooltip-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'tooltip-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'tooltip-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'tooltip-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'dock', detail: 'Dock', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'dock-label', detail: 'Text label for Dock Item', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'dock-active', detail: 'Makes the Dock Item look active', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dock-xs', detail: 'Extra Small Dock', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'dock-sm', detail: 'Small Dock', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'dock-md', detail: 'Medium Dock', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'dock-lg', detail: 'Large Dock', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'dock-xl', detail: 'Extra Large Dock', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'modal', detail: 'Modal', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'modal-box', detail: 'The content part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'modal-action', detail: 'Actions part (buttons, etc.)', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'modal-backdrop', detail: 'Label that covers the page when modal is open so we can close the modal by clicking outside', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'modal-toggle', detail: 'Hidden checkbox that controls the state of modal', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'modal-open', detail: 'Keeps the modal open (you can add this class using JS)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'modal-top', detail: 'Moves the modal to top', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'modal-middle', detail: 'Moves the modal to middle', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'modal-bottom', detail: 'Moves the modal to bottom', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'modal-start', detail: 'Moves the modal to start horizontally', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'modal-end', detail: 'Moves the modal to end horizontally', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'menu', detail: 'For <ul> tag', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'menu-title', detail: 'styles a <li> as title', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'menu-dropdown', detail: 'For the collapsible <ul> if you want to show it using JS', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'menu-dropdown-toggle', detail: 'For the toggle to show/hide the menu-dropdown using JS', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'menu-disabled', detail: 'For disabling a <li>', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'menu-active', detail: 'For the element inside <li> to look active', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'menu-focus', detail: 'For the element inside <li> to look focused', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'menu-dropdown-show', detail: 'Shows the menu-dropdown-toggle and menu-dropdown collapsible submenu using JS', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'menu-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'menu-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'menu-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'menu-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'menu-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'menu-vertical', detail: 'Vertical menu (default)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'menu-horizontal', detail: 'Horizontal menu', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'table', detail: 'For <table> tag', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'table-zebra', detail: 'For <table> to show zebra stripe rows', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'table-pin-rows', detail: 'For <table> to make all the rows inside <thead> and <tfoot> sticky', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'table-pin-cols', detail: 'For <table> to make all the <th> columns sticky', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'table-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'table-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'table-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'table-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'table-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'validator', detail: 'For input, select, textarea', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'validator-hint', detail: "for the hint text that appears after the input if it's invalid", kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'card', detail: 'Card', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'card-title', detail: 'Title part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'card-body', detail: 'Body part (content)', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'card-actions', detail: 'Actions part (buttons, etc.)', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'card-border', detail: 'Adds border to <card>', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'card-dash', detail: 'dash style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'card-side', detail: 'The image in <figure> will be on to the side', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'image-full', detail: 'The image in <figure> element will be the background', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'card-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'card-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'card-md', detail: 'Medium size (default)', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'card-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'card-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'breadcrumbs', detail: 'Wrapper around a <ul>', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'countdown', detail: 'Countdown wrapper', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'label', detail: 'For styling the text next to an input field (or select)', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'floating-label', detail: 'For the parent of an input field (or select) and a span that floats above the input field when the field is focused', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'rating', detail: 'For a div containing radio inputs', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'rating-half', detail: 'To shows half of the shapes. Useful for half star ratings', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'rating-hidden', detail: 'For the first radio to make it hidden so user can clear the rating', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'rating-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'rating-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'rating-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'rating-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'rating-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'collapse', detail: 'Collapse', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'collapse-title', detail: 'Title part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'collapse-content', detail: 'Content part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'collapse-arrow', detail: 'Adds arrow icon', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'collapse-plus', detail: 'Adds plus/minus icon', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'collapse-open', detail: 'Force open', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'collapse-close', detail: 'Force close', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'avatar', detail: 'Avatar', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'avatar-group', detail: 'Container for multiple avatars', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'avatar-online', detail: 'shows a green dot as online indicator', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'avatar-offline', detail: 'shows a gray dot as offline indicator', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'avatar-placeholder', detail: 'To show letters as avatar placeholder', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'mask', detail: 'Masks the content with shape', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'mask-squircle', detail: 'squircle', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-heart', detail: 'heart', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-hexagon', detail: 'hexagon vertical', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-hexagon-2', detail: 'hexagon horizontal', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-decagon', detail: 'decagon', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-pentagon', detail: 'pentagon', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-diamond', detail: 'diamond', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-square', detail: 'square', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-circle', detail: 'circle', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-star', detail: 'star', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-star-2', detail: 'star (bold)', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-triangle', detail: 'triangle pointing top', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-triangle-2', detail: 'triangle pointing down', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-triangle-3', detail: 'triangle pointing left', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-triangle-4', detail: 'triangle pointing right', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'mask-half-1', detail: 'Crops only the first half of mask', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'mask-half-2', detail: 'Crops only the second half of mask', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown', detail: 'Dropdown container', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'dropdown-content', detail: 'Content part', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'dropdown-start', detail: 'Align horizontally to start of button', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown-center', detail: 'Align horizontally to center of button', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown-end', detail: 'Align horizontally to end of button', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown-top', detail: 'Open from top', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown-bottom', detail: 'Open from bottom', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown-left', detail: 'Open from left', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown-right', detail: 'Open from right', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown-hover', detail: 'Opens on hover too', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'dropdown-open', detail: 'Force open', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'indicator', detail: 'Container element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'indicator-item', detail: 'will be placed on the corner of sibling', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'indicator-start', detail: 'align horizontally to the start', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'indicator-center', detail: 'align horizontally to the center', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'indicator-end', detail: 'align horizontally to the end', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'indicator-top', detail: 'align vertically to top', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'indicator-middle', detail: 'align vertically to middle', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'indicator-bottom', detail: 'align vertically to bottom', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'timeline', detail: 'Timeline container', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'timeline-start', detail: 'The content inside <li> that will be at the start direction', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'timeline-middle', detail: 'The content inside <li> that will be at the middle', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'timeline-end', detail: 'The content inside <li> that will be at the end direction', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'timeline-snap-icon', detail: 'snaps the icon to the start instead of middle', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'timeline-box', detail: 'Applies a box style to timeline-start or timeline-end', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'timeline-compact', detail: 'forces all items on one side', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'timeline-horizontal', detail: 'horizontal layout (default)', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'timeline-vertical', detail: 'vertical layout', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'input', detail: 'For <input type="text"> tag or a wrapper of <input type="text"> tag', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'input-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'input-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'input-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'input-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'input-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'input-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'input-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'input-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'input-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'input-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'input-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'input-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'input-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'input-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'footer', detail: 'Footer', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'footer-title', detail: 'Title of a footer column', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'footer-center', detail: 'Aligns footer content to center', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'footer-horizontal', detail: 'Puts footer columns next to each other horizontally', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'footer-vertical', detail: 'Puts footer columns under each other vertically', kind: CompletionItemKind.Value),
DaisyuiComponent(label: 'mockup-browser', detail: 'Browser mockup', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'mockup-browser-toolbar', detail: 'Toolbar part which can include addressbar, etc', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'status', detail: 'Status icon', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'status-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'status-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'status-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'status-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'status-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'status-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'status-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'status-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'status-xs', detail: 'extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'status-sm', detail: 'small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'status-md', detail: 'medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'status-lg', detail: 'large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'status-xl', detail: 'extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'file-input', detail: 'For <input type="file"> element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'file-input-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
DaisyuiComponent(label: 'file-input-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'file-input-primary', detail: 'primary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'file-input-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'file-input-accent', detail: 'accent color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'file-input-info', detail: 'info color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'file-input-success', detail: 'success color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'file-input-warning', detail: 'warning color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'file-input-error', detail: 'error color', kind: CompletionItemKind.Color),
DaisyuiComponent(label: 'file-input-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'file-input-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'file-input-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'file-input-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'file-input-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
DaisyuiComponent(label: 'diff', detail: 'Container element', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'diff-item-1', detail: 'First item', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'diff-item-2', detail: 'Second item', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'diff-resizer', detail: 'The resizer control', kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'filter', detail: 'For a HTML <form> or a <div> element that includes radio buttons for filtering items', kind: CompletionItemKind.Snippet),
DaisyuiComponent(label: 'filter-reset', detail: "An alternative to the reset button if you can't use a HTML form", kind: CompletionItemKind.Field),
DaisyuiComponent(label: 'theme-controller', detail: 'For a checkbox or radio input that must change the page theme', kind: CompletionItemKind.Snippet),
];
