// GENERATED CODE — DO NOT EDIT
import 'models.dart';

const components = <DaisyuiComponent>[
DaisyuiComponent(label: 'stats', detail: 'Container of multiple stat items'),
DaisyuiComponent(label: 'stat', detail: 'A block to display stat data about a topic'),
DaisyuiComponent(label: 'stat-title', detail: 'Title part'),
DaisyuiComponent(label: 'stat-value', detail: 'Value part'),
DaisyuiComponent(label: 'stat-desc', detail: 'Description part'),
DaisyuiComponent(label: 'stat-figure', detail: 'Figure part for icon, etc'),
DaisyuiComponent(label: 'stat-actions', detail: 'Actions part for button, etc'),
DaisyuiComponent(label: 'stats-horizontal', detail: 'Makes stats horizontal (default)'),
DaisyuiComponent(label: 'stats-vertical', detail: 'Makes stats vertical'),
DaisyuiComponent(label: 'select', detail: 'For <select> element'),
DaisyuiComponent(label: 'select-ghost', detail: 'ghost style'),
DaisyuiComponent(label: 'select-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'select-primary', detail: 'primary color'),
DaisyuiComponent(label: 'select-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'select-accent', detail: 'accent color'),
DaisyuiComponent(label: 'select-info', detail: 'info color'),
DaisyuiComponent(label: 'select-success', detail: 'success color'),
DaisyuiComponent(label: 'select-warning', detail: 'warning color'),
DaisyuiComponent(label: 'select-error', detail: 'error color'),
DaisyuiComponent(label: 'select-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'select-sm', detail: 'Small size'),
DaisyuiComponent(label: 'select-md', detail: 'Medium size'),
DaisyuiComponent(label: 'select-lg', detail: 'Large size'),
DaisyuiComponent(label: 'select-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'drawer', detail: 'The wrapper for sidebar and content'),
DaisyuiComponent(label: 'drawer-toggle', detail: 'The hidden checkbox that controls the state of drawer'),
DaisyuiComponent(label: 'drawer-content', detail: 'Content part'),
DaisyuiComponent(label: 'drawer-side', detail: 'Sidebar part'),
DaisyuiComponent(label: 'drawer-overlay', detail: 'Label that covers the page when drawer is open'),
DaisyuiComponent(label: 'drawer-end', detail: 'puts drawer to the other side'),
DaisyuiComponent(label: 'drawer-open', detail: 'Forces the drawer to be open'),
DaisyuiComponent(label: 'progress', detail: 'For <progress> tag'),
DaisyuiComponent(label: 'progress-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'progress-primary', detail: 'primary color'),
DaisyuiComponent(label: 'progress-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'progress-accent', detail: 'accent color'),
DaisyuiComponent(label: 'progress-info', detail: 'info color'),
DaisyuiComponent(label: 'progress-success', detail: 'success color'),
DaisyuiComponent(label: 'progress-warning', detail: 'warning color'),
DaisyuiComponent(label: 'progress-error', detail: 'error color'),
DaisyuiComponent(label: 'fieldset', detail: 'for the fieldset container'),
DaisyuiComponent(label: 'label', detail: 'label for inputs'),
DaisyuiComponent(label: 'fieldset-legend', detail: 'for the title of the fieldset'),
DaisyuiComponent(label: 'alert', detail: 'Container element'),
DaisyuiComponent(label: 'alert-outline', detail: 'outline style'),
DaisyuiComponent(label: 'alert-dash', detail: 'dash outline style'),
DaisyuiComponent(label: 'alert-soft', detail: 'soft style'),
DaisyuiComponent(label: 'alert-info', detail: 'info color'),
DaisyuiComponent(label: 'alert-success', detail: 'success color'),
DaisyuiComponent(label: 'alert-warning', detail: 'warning color'),
DaisyuiComponent(label: 'alert-error', detail: 'error color'),
DaisyuiComponent(label: 'alert-vertical', detail: 'Vertical layout, good for mobile'),
DaisyuiComponent(label: 'alert-horizontal', detail: 'Horizontal layout, good for desktop'),
DaisyuiComponent(label: 'divider', detail: 'A divider line between two elements'),
DaisyuiComponent(label: 'divider-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'divider-primary', detail: 'primary color'),
DaisyuiComponent(label: 'divider-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'divider-accent', detail: 'accent color'),
DaisyuiComponent(label: 'divider-success', detail: 'success color'),
DaisyuiComponent(label: 'divider-warning', detail: 'warning color'),
DaisyuiComponent(label: 'divider-info', detail: 'info color'),
DaisyuiComponent(label: 'divider-error', detail: 'error color'),
DaisyuiComponent(label: 'divider-vertical', detail: 'Divide vertical elements (on top of each other)'),
DaisyuiComponent(label: 'divider-horizontal', detail: 'Divide horizontal elements (next to each other)'),
DaisyuiComponent(label: 'divider-start', detail: 'Pushes the divider text to the start'),
DaisyuiComponent(label: 'divider-end', detail: 'Pushes the divider text to the end'),
DaisyuiComponent(label: 'hero', detail: 'Hero container'),
DaisyuiComponent(label: 'hero-content', detail: 'content part'),
DaisyuiComponent(label: 'hero-overlay', detail: 'Overlay that covers the background image'),
DaisyuiComponent(label: 'link', detail: 'Adds underline'),
DaisyuiComponent(label: 'link-hover', detail: 'Only shows underline on hover'),
DaisyuiComponent(label: 'link-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'link-primary', detail: 'primary color'),
DaisyuiComponent(label: 'link-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'link-accent', detail: 'accent color'),
DaisyuiComponent(label: 'link-success', detail: 'success color'),
DaisyuiComponent(label: 'link-info', detail: 'info color'),
DaisyuiComponent(label: 'link-warning', detail: 'warning color'),
DaisyuiComponent(label: 'link-error', detail: 'error color'),
DaisyuiComponent(label: 'kbd', detail: 'Do show a keyboard key or a shortcut key'),
DaisyuiComponent(label: 'kbd-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'kbd-sm', detail: 'Small size'),
DaisyuiComponent(label: 'kbd-md', detail: 'Medium size'),
DaisyuiComponent(label: 'kbd-lg', detail: 'Large size'),
DaisyuiComponent(label: 'kbd-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'mockup-code', detail: 'Code terminal mockup'),
DaisyuiComponent(label: 'loading', detail: 'Loading element'),
DaisyuiComponent(label: 'loading-spinner', detail: 'spinner animation'),
DaisyuiComponent(label: 'loading-dots', detail: 'dots animation'),
DaisyuiComponent(label: 'loading-ring', detail: 'ring animation'),
DaisyuiComponent(label: 'loading-ball', detail: 'ball animation'),
DaisyuiComponent(label: 'loading-bars', detail: 'bars animation'),
DaisyuiComponent(label: 'loading-infinity', detail: 'infinity animation'),
DaisyuiComponent(label: 'loading-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'loading-sm', detail: 'Small size'),
DaisyuiComponent(label: 'loading-md', detail: 'Medium size'),
DaisyuiComponent(label: 'loading-lg', detail: 'Large size'),
DaisyuiComponent(label: 'loading-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'skeleton', detail: 'A placeholder div with loading animation'),
DaisyuiComponent(label: 'swap', detail: 'Swap container'),
DaisyuiComponent(label: 'swap-on', detail: 'The child element that should be visible when checkbox is checked or when swap is active'),
DaisyuiComponent(label: 'swap-off', detail: 'The child element that should be visible when checkbox is not checked or when swap is not active'),
DaisyuiComponent(label: 'swap-indeterminate', detail: 'The child element that should be visible when checkbox is indeterminate'),
DaisyuiComponent(label: 'swap-active', detail: 'Activates the swap (no need for checkbox)'),
DaisyuiComponent(label: 'swap-rotate', detail: 'Adds rotate effect to swap'),
DaisyuiComponent(label: 'swap-flip', detail: 'Adds flip effect to swap'),
DaisyuiComponent(label: 'badge', detail: 'Container element'),
DaisyuiComponent(label: 'badge-outline', detail: 'outline style'),
DaisyuiComponent(label: 'badge-dash', detail: 'dash outline style'),
DaisyuiComponent(label: 'badge-soft', detail: 'soft style'),
DaisyuiComponent(label: 'badge-ghost', detail: 'ghost style'),
DaisyuiComponent(label: 'badge-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'badge-primary', detail: 'primary color'),
DaisyuiComponent(label: 'badge-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'badge-accent', detail: 'accent color'),
DaisyuiComponent(label: 'badge-info', detail: 'info color'),
DaisyuiComponent(label: 'badge-success', detail: 'success color'),
DaisyuiComponent(label: 'badge-warning', detail: 'warning color'),
DaisyuiComponent(label: 'badge-error', detail: 'error color'),
DaisyuiComponent(label: 'badge-xs', detail: 'extra small size'),
DaisyuiComponent(label: 'badge-sm', detail: 'small size'),
DaisyuiComponent(label: 'badge-md', detail: 'medium size (default)'),
DaisyuiComponent(label: 'badge-lg', detail: 'large size'),
DaisyuiComponent(label: 'badge-xl', detail: 'extra large size'),
DaisyuiComponent(label: 'radio', detail: 'For radio input'),
DaisyuiComponent(label: 'radio-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'radio-primary', detail: 'primary color'),
DaisyuiComponent(label: 'radio-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'radio-accent', detail: 'accent color'),
DaisyuiComponent(label: 'radio-success', detail: 'success color'),
DaisyuiComponent(label: 'radio-warning', detail: 'warning color'),
DaisyuiComponent(label: 'radio-info', detail: 'info color'),
DaisyuiComponent(label: 'radio-error', detail: 'error color'),
DaisyuiComponent(label: 'radio-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'radio-sm', detail: 'Small size'),
DaisyuiComponent(label: 'radio-md', detail: 'Medium size'),
DaisyuiComponent(label: 'radio-lg', detail: 'Large size'),
DaisyuiComponent(label: 'radio-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'navbar', detail: 'Navigation bar'),
DaisyuiComponent(label: 'navbar-start', detail: 'For the div inside navbar, to fill 50% of width'),
DaisyuiComponent(label: 'navbar-center', detail: 'For the div inside navbar, to be at center horizontally'),
DaisyuiComponent(label: 'navbar-end', detail: 'For the div inside navbar, to fill second 50% of width'),
DaisyuiComponent(label: 'collapse', detail: 'Collapse'),
DaisyuiComponent(label: 'collapse-title', detail: 'Title part'),
DaisyuiComponent(label: 'collapse-content', detail: 'Content part'),
DaisyuiComponent(label: 'collapse-arrow', detail: 'Adds arrow icon'),
DaisyuiComponent(label: 'collapse-plus', detail: 'Adds plus/minus icon'),
DaisyuiComponent(label: 'collapse-open', detail: 'Force open'),
DaisyuiComponent(label: 'collapse-close', detail: 'Force close'),
DaisyuiComponent(label: 'textarea', detail: 'For <textarea> element'),
DaisyuiComponent(label: 'textarea-ghost', detail: 'ghost style'),
DaisyuiComponent(label: 'textarea-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'textarea-primary', detail: 'primary color'),
DaisyuiComponent(label: 'textarea-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'textarea-accent', detail: 'accent color'),
DaisyuiComponent(label: 'textarea-info', detail: 'info color'),
DaisyuiComponent(label: 'textarea-success', detail: 'success color'),
DaisyuiComponent(label: 'textarea-warning', detail: 'warning color'),
DaisyuiComponent(label: 'textarea-error', detail: 'error color'),
DaisyuiComponent(label: 'textarea-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'textarea-sm', detail: 'Small size'),
DaisyuiComponent(label: 'textarea-md', detail: 'Medium size'),
DaisyuiComponent(label: 'textarea-lg', detail: 'Large size'),
DaisyuiComponent(label: 'textarea-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'btn', detail: 'Button'),
DaisyuiComponent(label: 'btn-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'btn-primary', detail: 'primary color'),
DaisyuiComponent(label: 'btn-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'btn-accent', detail: 'accent color'),
DaisyuiComponent(label: 'btn-info', detail: 'info color'),
DaisyuiComponent(label: 'btn-success', detail: 'success color'),
DaisyuiComponent(label: 'btn-warning', detail: 'warning color'),
DaisyuiComponent(label: 'btn-error', detail: 'error color'),
DaisyuiComponent(label: 'btn-outline', detail: 'outline style'),
DaisyuiComponent(label: 'btn-dash', detail: 'dash style'),
DaisyuiComponent(label: 'btn-soft', detail: 'soft style'),
DaisyuiComponent(label: 'btn-ghost', detail: 'ghost style'),
DaisyuiComponent(label: 'btn-link', detail: 'looks like a link'),
DaisyuiComponent(label: 'btn-active', detail: 'looks active'),
DaisyuiComponent(label: 'btn-disabled', detail: 'looks disabled'),
DaisyuiComponent(label: 'btn-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'btn-sm', detail: 'Small size'),
DaisyuiComponent(label: 'btn-md', detail: 'Medium size (default)'),
DaisyuiComponent(label: 'btn-lg', detail: 'Large size'),
DaisyuiComponent(label: 'btn-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'btn-wide', detail: 'more horizontal padding'),
DaisyuiComponent(label: 'btn-block', detail: 'Full width'),
DaisyuiComponent(label: 'btn-square', detail: '1:1 ratio'),
DaisyuiComponent(label: 'btn-circle', detail: '1:1 ratio with rounded corners'),
DaisyuiComponent(label: 'chat', detail: 'Container for one line of conversation and its data'),
DaisyuiComponent(label: 'chat-image', detail: 'Author image'),
DaisyuiComponent(label: 'chat-header', detail: 'Text above the chat bubble'),
DaisyuiComponent(label: 'chat-footer', detail: 'Text below the chat bubble'),
DaisyuiComponent(label: 'chat-bubble', detail: 'Chat bubble'),
DaisyuiComponent(label: 'chat-start', detail: 'Aligns chat to start horizontally (required)'),
DaisyuiComponent(label: 'chat-end', detail: 'Aligns chat to end horizontally (required)'),
DaisyuiComponent(label: 'chat-bubble-neutral', detail: 'neutral color for chat-bubble'),
DaisyuiComponent(label: 'chat-bubble-primary', detail: 'primary color for chat-bubble'),
DaisyuiComponent(label: 'chat-bubble-secondary', detail: 'secondary color for chat-bubble'),
DaisyuiComponent(label: 'chat-bubble-accent', detail: 'accent color for chat-bubble'),
DaisyuiComponent(label: 'chat-bubble-info', detail: 'info color for chat-bubble'),
DaisyuiComponent(label: 'chat-bubble-success', detail: 'success color for chat-bubble'),
DaisyuiComponent(label: 'chat-bubble-warning', detail: 'warning color for chat-bubble'),
DaisyuiComponent(label: 'chat-bubble-error', detail: 'error color for chat-bubble'),
DaisyuiComponent(label: 'tabs', detail: 'Container of multiple tab items'),
DaisyuiComponent(label: 'tab', detail: 'A single tab button (can be button, link, div, radio input, etc)'),
DaisyuiComponent(label: 'tab-content', detail: 'Tab content that comes immediately after a tab'),
DaisyuiComponent(label: 'tabs-box', detail: 'box style'),
DaisyuiComponent(label: 'tabs-border', detail: 'bottom border style'),
DaisyuiComponent(label: 'tabs-lift', detail: 'lift style'),
DaisyuiComponent(label: 'tab-active', detail: 'Makes a single tab look active'),
DaisyuiComponent(label: 'tab-disabled', detail: 'Makes a single tab look disabled'),
DaisyuiComponent(label: 'tabs-top', detail: 'Puts tab buttons on top of the tab-content (default)'),
DaisyuiComponent(label: 'tabs-bottom', detail: 'Puts tabs on under the tab-content'),
DaisyuiComponent(label: 'tabs-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'tabs-sm', detail: 'Small size'),
DaisyuiComponent(label: 'tabs-md', detail: 'Medium size'),
DaisyuiComponent(label: 'tabs-lg', detail: 'Large size'),
DaisyuiComponent(label: 'tabs-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'stack', detail: 'Puts the children elements on top of each other'),
DaisyuiComponent(label: 'stack-top', detail: 'Aligns the children elements to the top'),
DaisyuiComponent(label: 'stack-bottom', detail: 'Aligns the children elements to the bottom'),
DaisyuiComponent(label: 'stack-start', detail: 'Aligns the children elements to the start (horizontally)'),
DaisyuiComponent(label: 'stack-end', detail: 'Aligns the children elements to the end (horizontally)'),
DaisyuiComponent(label: 'join', detail: 'For grouping multiple items'),
DaisyuiComponent(label: 'join-item', detail: 'Item inside join. Can be a button, input, etc.'),
DaisyuiComponent(label: 'join-vertical', detail: 'Show items vertically'),
DaisyuiComponent(label: 'join-horizontal', detail: 'Show items horizontally'),
DaisyuiComponent(label: 'range', detail: 'For <input type="range"> tag'),
DaisyuiComponent(label: 'range-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'range-primary', detail: 'primary color'),
DaisyuiComponent(label: 'range-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'range-accent', detail: 'accent color'),
DaisyuiComponent(label: 'range-success', detail: 'success color'),
DaisyuiComponent(label: 'range-warning', detail: 'warning color'),
DaisyuiComponent(label: 'range-info', detail: 'info color'),
DaisyuiComponent(label: 'range-error', detail: 'error color'),
DaisyuiComponent(label: 'range-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'range-sm', detail: 'Small size'),
DaisyuiComponent(label: 'range-md', detail: 'Medium size'),
DaisyuiComponent(label: 'range-lg', detail: 'Large size'),
DaisyuiComponent(label: 'range-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'checkbox', detail: 'Checkbox'),
DaisyuiComponent(label: 'checkbox-primary', detail: 'primary color'),
DaisyuiComponent(label: 'checkbox-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'checkbox-accent', detail: 'accent color'),
DaisyuiComponent(label: 'checkbox-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'checkbox-success', detail: 'success color'),
DaisyuiComponent(label: 'checkbox-warning', detail: 'warning color'),
DaisyuiComponent(label: 'checkbox-info', detail: 'info color'),
DaisyuiComponent(label: 'checkbox-error', detail: 'error color'),
DaisyuiComponent(label: 'checkbox-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'checkbox-sm', detail: 'Small size'),
DaisyuiComponent(label: 'checkbox-md', detail: 'Medium size'),
DaisyuiComponent(label: 'checkbox-lg', detail: 'Large size'),
DaisyuiComponent(label: 'checkbox-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'radial-progress', detail: 'Shows a radial progress'),
DaisyuiComponent(label: 'toast', detail: 'Container element that sticks to the corner of page'),
DaisyuiComponent(label: 'toast-start', detail: 'align horizontally to the left'),
DaisyuiComponent(label: 'toast-center', detail: 'align horizontally to the center'),
DaisyuiComponent(label: 'toast-end', detail: 'align horizontally to the right'),
DaisyuiComponent(label: 'toast-top', detail: 'align vertically to top'),
DaisyuiComponent(label: 'toast-middle', detail: 'align vertically to middle'),
DaisyuiComponent(label: 'toast-bottom', detail: 'align vertically to bottom'),
DaisyuiComponent(label: 'steps', detail: 'Container of multiple step nodes'),
DaisyuiComponent(label: 'step', detail: 'A single step node'),
DaisyuiComponent(label: 'step-icon', detail: 'For custom icon inside step'),
DaisyuiComponent(label: 'step-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'step-primary', detail: 'primary color'),
DaisyuiComponent(label: 'step-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'step-accent', detail: 'accent color'),
DaisyuiComponent(label: 'step-info', detail: 'info color'),
DaisyuiComponent(label: 'step-success', detail: 'success color'),
DaisyuiComponent(label: 'step-warning', detail: 'warning color'),
DaisyuiComponent(label: 'step-error', detail: 'error color'),
DaisyuiComponent(label: 'steps-vertical', detail: 'Makes steps vertical (default)'),
DaisyuiComponent(label: 'steps-horizontal', detail: 'Makes steps horizontal'),
DaisyuiComponent(label: 'cally', detail: 'for Cally web component'),
DaisyuiComponent(label: 'pika-single', detail: 'for the input field that opens Pikaday calendar'),
DaisyuiComponent(label: 'react-day-picker', detail: 'for the DayPicker component'),
DaisyuiComponent(label: 'toggle', detail: 'For <input type="checkbox">'),
DaisyuiComponent(label: 'toggle-primary', detail: 'primary color'),
DaisyuiComponent(label: 'toggle-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'toggle-accent', detail: 'accent color'),
DaisyuiComponent(label: 'toggle-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'toggle-success', detail: 'success color'),
DaisyuiComponent(label: 'toggle-warning', detail: 'warning color'),
DaisyuiComponent(label: 'toggle-info', detail: 'info color'),
DaisyuiComponent(label: 'toggle-error', detail: 'error color'),
DaisyuiComponent(label: 'toggle-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'toggle-sm', detail: 'Small size'),
DaisyuiComponent(label: 'toggle-md', detail: 'Medium size'),
DaisyuiComponent(label: 'toggle-lg', detail: 'Large size'),
DaisyuiComponent(label: 'toggle-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'join', detail: 'For grouping multiple items'),
DaisyuiComponent(label: 'join-item', detail: 'Item inside join. Can be a button, input, etc.'),
DaisyuiComponent(label: 'join-vertical', detail: 'Show items vertically'),
DaisyuiComponent(label: 'join-horizontal', detail: 'Show items horizontally'),
DaisyuiComponent(label: 'mockup-phone', detail: 'Phone mockup'),
DaisyuiComponent(label: 'mockup-phone-camera', detail: 'Camera part'),
DaisyuiComponent(label: 'mockup-phone-display', detail: 'Display part'),
DaisyuiComponent(label: 'mockup-window', detail: 'OS window mockup'),
DaisyuiComponent(label: 'carousel', detail: 'Carousel container'),
DaisyuiComponent(label: 'carousel-item', detail: 'Carousel item'),
DaisyuiComponent(label: 'carousel-start', detail: 'Snap elements to start'),
DaisyuiComponent(label: 'carousel-center', detail: 'Snap elements to center'),
DaisyuiComponent(label: 'carousel-end', detail: 'Snap elements to end'),
DaisyuiComponent(label: 'carousel-horizontal', detail: 'Horizontal layout (default)'),
DaisyuiComponent(label: 'carousel-vertical', detail: 'Vertical layout'),
DaisyuiComponent(label: 'list', detail: 'A vertical flex layout to include list rows'),
DaisyuiComponent(label: 'list-row', detail: 'The item inside list. A horizontal grid layout to include data'),
DaisyuiComponent(label: 'list-col-wrap', detail: 'For one of direct children of list-row to push it to the next line'),
DaisyuiComponent(label: 'list-col-grow', detail: 'For one of direct children of list-row to make it fill the remaining space'),
DaisyuiComponent(label: 'tooltip', detail: 'Container element'),
DaisyuiComponent(label: 'tooltip-content', detail: 'Optional. Setting a div as the content of the tooltip instead of the `data-tip` text'),
DaisyuiComponent(label: 'tooltip-top', detail: 'Put tooltip on top'),
DaisyuiComponent(label: 'tooltip-bottom', detail: 'Put tooltip on bottom'),
DaisyuiComponent(label: 'tooltip-left', detail: 'Put tooltip on left'),
DaisyuiComponent(label: 'tooltip-right', detail: 'Put tooltip on right'),
DaisyuiComponent(label: 'tooltip-open', detail: 'Force open tooltip'),
DaisyuiComponent(label: 'tooltip-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'tooltip-primary', detail: 'primary color'),
DaisyuiComponent(label: 'tooltip-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'tooltip-accent', detail: 'accent color'),
DaisyuiComponent(label: 'tooltip-info', detail: 'info color'),
DaisyuiComponent(label: 'tooltip-success', detail: 'success color'),
DaisyuiComponent(label: 'tooltip-warning', detail: 'warning color'),
DaisyuiComponent(label: 'tooltip-error', detail: 'error color'),
DaisyuiComponent(label: 'dock', detail: 'Dock'),
DaisyuiComponent(label: 'dock-label', detail: 'Text label for Dock Item'),
DaisyuiComponent(label: 'dock-active', detail: 'Makes the Dock Item look active'),
DaisyuiComponent(label: 'dock-xs', detail: 'Extra Small Dock'),
DaisyuiComponent(label: 'dock-sm', detail: 'Small Dock'),
DaisyuiComponent(label: 'dock-md', detail: 'Medium Dock'),
DaisyuiComponent(label: 'dock-lg', detail: 'Large Dock'),
DaisyuiComponent(label: 'dock-xl', detail: 'Extra Large Dock'),
DaisyuiComponent(label: 'modal', detail: 'Modal'),
DaisyuiComponent(label: 'modal-box', detail: 'The content part'),
DaisyuiComponent(label: 'modal-action', detail: 'Actions part (buttons, etc.)'),
DaisyuiComponent(label: 'modal-backdrop', detail: 'Label that covers the page when modal is open so we can close the modal by clicking outside'),
DaisyuiComponent(label: 'modal-toggle', detail: 'Hidden checkbox that controls the state of modal'),
DaisyuiComponent(label: 'modal-open', detail: 'Keeps the modal open (you can add this class using JS)'),
DaisyuiComponent(label: 'modal-top', detail: 'Moves the modal to top'),
DaisyuiComponent(label: 'modal-middle', detail: 'Moves the modal to middle'),
DaisyuiComponent(label: 'modal-bottom', detail: 'Moves the modal to bottom'),
DaisyuiComponent(label: 'modal-start', detail: 'Moves the modal to start horizontally'),
DaisyuiComponent(label: 'modal-end', detail: 'Moves the modal to end horizontally'),
DaisyuiComponent(label: 'menu', detail: 'For <ul> tag'),
DaisyuiComponent(label: 'menu-title', detail: 'styles a <li> as title'),
DaisyuiComponent(label: 'menu-dropdown', detail: 'For the collapsible <ul> if you want to show it using JS'),
DaisyuiComponent(label: 'menu-dropdown-toggle', detail: 'For the toggle to show/hide the menu-dropdown using JS'),
DaisyuiComponent(label: 'menu-disabled', detail: 'For disabling a <li>'),
DaisyuiComponent(label: 'menu-active', detail: 'For the element inside <li> to look active'),
DaisyuiComponent(label: 'menu-focus', detail: 'For the element inside <li> to look focused'),
DaisyuiComponent(label: 'menu-dropdown-show', detail: 'Shows the menu-dropdown-toggle and menu-dropdown collapsible submenu using JS'),
DaisyuiComponent(label: 'menu-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'menu-sm', detail: 'Small size'),
DaisyuiComponent(label: 'menu-md', detail: 'Medium size'),
DaisyuiComponent(label: 'menu-lg', detail: 'Large size'),
DaisyuiComponent(label: 'menu-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'menu-vertical', detail: 'Vertical menu (default)'),
DaisyuiComponent(label: 'menu-horizontal', detail: 'Horizontal menu'),
DaisyuiComponent(label: 'table', detail: 'For <table> tag'),
DaisyuiComponent(label: 'table-zebra', detail: 'For <table> to show zebra stripe rows'),
DaisyuiComponent(label: 'table-pin-rows', detail: 'For <table> to make all the rows inside <thead> and <tfoot> sticky'),
DaisyuiComponent(label: 'table-pin-cols', detail: 'For <table> to make all the <th> columns sticky'),
DaisyuiComponent(label: 'table-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'table-sm', detail: 'Small size'),
DaisyuiComponent(label: 'table-md', detail: 'Medium size'),
DaisyuiComponent(label: 'table-lg', detail: 'Large size'),
DaisyuiComponent(label: 'table-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'validator', detail: 'For input, select, textarea'),
DaisyuiComponent(label: 'validator-hint', detail: "for the hint text that appears after the input if it's invalid"),
DaisyuiComponent(label: 'card', detail: 'Card'),
DaisyuiComponent(label: 'card-title', detail: 'Title part'),
DaisyuiComponent(label: 'card-body', detail: 'Body part (content)'),
DaisyuiComponent(label: 'card-actions', detail: 'Actions part (buttons, etc.)'),
DaisyuiComponent(label: 'card-border', detail: 'Adds border to <card>'),
DaisyuiComponent(label: 'card-dash', detail: 'dash style'),
DaisyuiComponent(label: 'card-side', detail: 'The image in <figure> will be on to the side'),
DaisyuiComponent(label: 'image-full', detail: 'The image in <figure> element will be the background'),
DaisyuiComponent(label: 'card-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'card-sm', detail: 'Small size'),
DaisyuiComponent(label: 'card-md', detail: 'Medium size (default)'),
DaisyuiComponent(label: 'card-lg', detail: 'Large size'),
DaisyuiComponent(label: 'card-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'breadcrumbs', detail: 'Wrapper around a <ul>'),
DaisyuiComponent(label: 'countdown', detail: 'Countdown wrapper'),
DaisyuiComponent(label: 'label', detail: 'For styling the text next to an input field (or select)'),
DaisyuiComponent(label: 'floating-label', detail: 'For the parent of an input field (or select) and a span that floats above the input field when the field is focused'),
DaisyuiComponent(label: 'rating', detail: 'For a div containing radio inputs'),
DaisyuiComponent(label: 'rating-half', detail: 'To shows half of the shapes. Useful for half star ratings'),
DaisyuiComponent(label: 'rating-hidden', detail: 'For the first radio to make it hidden so user can clear the rating'),
DaisyuiComponent(label: 'rating-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'rating-sm', detail: 'Small size'),
DaisyuiComponent(label: 'rating-md', detail: 'Medium size'),
DaisyuiComponent(label: 'rating-lg', detail: 'Large size'),
DaisyuiComponent(label: 'rating-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'collapse', detail: 'Collapse'),
DaisyuiComponent(label: 'collapse-title', detail: 'Title part'),
DaisyuiComponent(label: 'collapse-content', detail: 'Content part'),
DaisyuiComponent(label: 'collapse-arrow', detail: 'Adds arrow icon'),
DaisyuiComponent(label: 'collapse-plus', detail: 'Adds plus/minus icon'),
DaisyuiComponent(label: 'collapse-open', detail: 'Force open'),
DaisyuiComponent(label: 'collapse-close', detail: 'Force close'),
DaisyuiComponent(label: 'avatar', detail: 'Avatar'),
DaisyuiComponent(label: 'avatar-group', detail: 'Container for multiple avatars'),
DaisyuiComponent(label: 'avatar-online', detail: 'shows a green dot as online indicator'),
DaisyuiComponent(label: 'avatar-offline', detail: 'shows a gray dot as offline indicator'),
DaisyuiComponent(label: 'avatar-placeholder', detail: 'To show letters as avatar placeholder'),
DaisyuiComponent(label: 'mask', detail: 'Masks the content with shape'),
DaisyuiComponent(label: 'mask-squircle', detail: 'squircle'),
DaisyuiComponent(label: 'mask-heart', detail: 'heart'),
DaisyuiComponent(label: 'mask-hexagon', detail: 'hexagon vertical'),
DaisyuiComponent(label: 'mask-hexagon-2', detail: 'hexagon horizontal'),
DaisyuiComponent(label: 'mask-decagon', detail: 'decagon'),
DaisyuiComponent(label: 'mask-pentagon', detail: 'pentagon'),
DaisyuiComponent(label: 'mask-diamond', detail: 'diamond'),
DaisyuiComponent(label: 'mask-square', detail: 'square'),
DaisyuiComponent(label: 'mask-circle', detail: 'circle'),
DaisyuiComponent(label: 'mask-star', detail: 'star'),
DaisyuiComponent(label: 'mask-star-2', detail: 'star (bold)'),
DaisyuiComponent(label: 'mask-triangle', detail: 'triangle pointing top'),
DaisyuiComponent(label: 'mask-triangle-2', detail: 'triangle pointing down'),
DaisyuiComponent(label: 'mask-triangle-3', detail: 'triangle pointing left'),
DaisyuiComponent(label: 'mask-triangle-4', detail: 'triangle pointing right'),
DaisyuiComponent(label: 'mask-half-1', detail: 'Crops only the first half of mask'),
DaisyuiComponent(label: 'mask-half-2', detail: 'Crops only the second half of mask'),
DaisyuiComponent(label: 'dropdown', detail: 'Dropdown container'),
DaisyuiComponent(label: 'dropdown-content', detail: 'Content part'),
DaisyuiComponent(label: 'dropdown-start', detail: 'Align horizontally to start of button'),
DaisyuiComponent(label: 'dropdown-center', detail: 'Align horizontally to center of button'),
DaisyuiComponent(label: 'dropdown-end', detail: 'Align horizontally to end of button'),
DaisyuiComponent(label: 'dropdown-top', detail: 'Open from top'),
DaisyuiComponent(label: 'dropdown-bottom', detail: 'Open from bottom'),
DaisyuiComponent(label: 'dropdown-left', detail: 'Open from left'),
DaisyuiComponent(label: 'dropdown-right', detail: 'Open from right'),
DaisyuiComponent(label: 'dropdown-hover', detail: 'Opens on hover too'),
DaisyuiComponent(label: 'dropdown-open', detail: 'Force open'),
DaisyuiComponent(label: 'indicator', detail: 'Container element'),
DaisyuiComponent(label: 'indicator-item', detail: 'will be placed on the corner of sibling'),
DaisyuiComponent(label: 'indicator-start', detail: 'align horizontally to the start'),
DaisyuiComponent(label: 'indicator-center', detail: 'align horizontally to the center'),
DaisyuiComponent(label: 'indicator-end', detail: 'align horizontally to the end'),
DaisyuiComponent(label: 'indicator-top', detail: 'align vertically to top'),
DaisyuiComponent(label: 'indicator-middle', detail: 'align vertically to middle'),
DaisyuiComponent(label: 'indicator-bottom', detail: 'align vertically to bottom'),
DaisyuiComponent(label: 'timeline', detail: 'Timeline container'),
DaisyuiComponent(label: 'timeline-start', detail: 'The content inside <li> that will be at the start direction'),
DaisyuiComponent(label: 'timeline-middle', detail: 'The content inside <li> that will be at the middle'),
DaisyuiComponent(label: 'timeline-end', detail: 'The content inside <li> that will be at the end direction'),
DaisyuiComponent(label: 'timeline-snap-icon', detail: 'snaps the icon to the start instead of middle'),
DaisyuiComponent(label: 'timeline-box', detail: 'Applies a box style to timeline-start or timeline-end'),
DaisyuiComponent(label: 'timeline-compact', detail: 'forces all items on one side'),
DaisyuiComponent(label: 'timeline-horizontal', detail: 'horizontal layout (default)'),
DaisyuiComponent(label: 'timeline-vertical', detail: 'vertical layout'),
DaisyuiComponent(label: 'input', detail: 'For <input type="text"> tag or a wrapper of <input type="text"> tag'),
DaisyuiComponent(label: 'input-ghost', detail: 'ghost style'),
DaisyuiComponent(label: 'input-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'input-primary', detail: 'primary color'),
DaisyuiComponent(label: 'input-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'input-accent', detail: 'accent color'),
DaisyuiComponent(label: 'input-info', detail: 'info color'),
DaisyuiComponent(label: 'input-success', detail: 'success color'),
DaisyuiComponent(label: 'input-warning', detail: 'warning color'),
DaisyuiComponent(label: 'input-error', detail: 'error color'),
DaisyuiComponent(label: 'input-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'input-sm', detail: 'Small size'),
DaisyuiComponent(label: 'input-md', detail: 'Medium size'),
DaisyuiComponent(label: 'input-lg', detail: 'Large size'),
DaisyuiComponent(label: 'input-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'footer', detail: 'Footer'),
DaisyuiComponent(label: 'footer-title', detail: 'Title of a footer column'),
DaisyuiComponent(label: 'footer-center', detail: 'Aligns footer content to center'),
DaisyuiComponent(label: 'footer-horizontal', detail: 'Puts footer columns next to each other horizontally'),
DaisyuiComponent(label: 'footer-vertical', detail: 'Puts footer columns under each other vertically'),
DaisyuiComponent(label: 'mockup-browser', detail: 'Browser mockup'),
DaisyuiComponent(label: 'mockup-browser-toolbar', detail: 'Toolbar part which can include addressbar, etc'),
DaisyuiComponent(label: 'status', detail: 'Status icon'),
DaisyuiComponent(label: 'status-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'status-primary', detail: 'primary color'),
DaisyuiComponent(label: 'status-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'status-accent', detail: 'accent color'),
DaisyuiComponent(label: 'status-info', detail: 'info color'),
DaisyuiComponent(label: 'status-success', detail: 'success color'),
DaisyuiComponent(label: 'status-warning', detail: 'warning color'),
DaisyuiComponent(label: 'status-error', detail: 'error color'),
DaisyuiComponent(label: 'status-xs', detail: 'extra small size'),
DaisyuiComponent(label: 'status-sm', detail: 'small size'),
DaisyuiComponent(label: 'status-md', detail: 'medium size'),
DaisyuiComponent(label: 'status-lg', detail: 'large size'),
DaisyuiComponent(label: 'status-xl', detail: 'extra large size'),
DaisyuiComponent(label: 'file-input', detail: 'For <input type="file"> element'),
DaisyuiComponent(label: 'file-input-ghost', detail: 'ghost style'),
DaisyuiComponent(label: 'file-input-neutral', detail: 'neutral color'),
DaisyuiComponent(label: 'file-input-primary', detail: 'primary color'),
DaisyuiComponent(label: 'file-input-secondary', detail: 'secondary color'),
DaisyuiComponent(label: 'file-input-accent', detail: 'accent color'),
DaisyuiComponent(label: 'file-input-info', detail: 'info color'),
DaisyuiComponent(label: 'file-input-success', detail: 'success color'),
DaisyuiComponent(label: 'file-input-warning', detail: 'warning color'),
DaisyuiComponent(label: 'file-input-error', detail: 'error color'),
DaisyuiComponent(label: 'file-input-xs', detail: 'Extra small size'),
DaisyuiComponent(label: 'file-input-sm', detail: 'Small size'),
DaisyuiComponent(label: 'file-input-md', detail: 'Medium size'),
DaisyuiComponent(label: 'file-input-lg', detail: 'Large size'),
DaisyuiComponent(label: 'file-input-xl', detail: 'Extra large size'),
DaisyuiComponent(label: 'diff', detail: 'Container element'),
DaisyuiComponent(label: 'diff-item-1', detail: 'First item'),
DaisyuiComponent(label: 'diff-item-2', detail: 'Second item'),
DaisyuiComponent(label: 'diff-resizer', detail: 'The resizer control'),
DaisyuiComponent(label: 'filter', detail: 'For a HTML <form> or a <div> element that includes radio buttons for filtering items'),
DaisyuiComponent(label: 'filter-reset', detail: "An alternative to the reset button if you can't use a HTML form"),
DaisyuiComponent(label: 'theme-controller', detail: 'For a checkbox or radio input that must change the page theme'),
];
