// GENERATED CODE — DO NOT EDIT
import 'package:lsp_server/lsp_server.dart';
import 'models.dart';

const Map<String, DaisyuiComponent> components = <String, DaisyuiComponent>{
'stats': DaisyuiComponent(label: 'stats', detail: 'Container of multiple stat items', kind: CompletionItemKind.Constant),
'stat': DaisyuiComponent(label: 'stat', detail: 'A block to display stat data about a topic', kind: CompletionItemKind.Field),
'stat-title': DaisyuiComponent(label: 'stat-title', detail: 'Title part', kind: CompletionItemKind.Field),
'stat-value': DaisyuiComponent(label: 'stat-value', detail: 'Value part', kind: CompletionItemKind.Field),
'stat-desc': DaisyuiComponent(label: 'stat-desc', detail: 'Description part', kind: CompletionItemKind.Field),
'stat-figure': DaisyuiComponent(label: 'stat-figure', detail: 'Figure part for icon, etc', kind: CompletionItemKind.Field),
'stat-actions': DaisyuiComponent(label: 'stat-actions', detail: 'Actions part for button, etc', kind: CompletionItemKind.Field),
'stats-horizontal': DaisyuiComponent(label: 'stats-horizontal', detail: 'Makes stats horizontal (default)', kind: CompletionItemKind.Value),
'stats-vertical': DaisyuiComponent(label: 'stats-vertical', detail: 'Makes stats vertical', kind: CompletionItemKind.Value),
'select': DaisyuiComponent(label: 'select', detail: 'For <select> element', kind: CompletionItemKind.Constant),
'select-ghost': DaisyuiComponent(label: 'select-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
'select-neutral': DaisyuiComponent(label: 'select-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'select-primary': DaisyuiComponent(label: 'select-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'select-secondary': DaisyuiComponent(label: 'select-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'select-accent': DaisyuiComponent(label: 'select-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'select-info': DaisyuiComponent(label: 'select-info', detail: 'info color', kind: CompletionItemKind.Color),
'select-success': DaisyuiComponent(label: 'select-success', detail: 'success color', kind: CompletionItemKind.Color),
'select-warning': DaisyuiComponent(label: 'select-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'select-error': DaisyuiComponent(label: 'select-error', detail: 'error color', kind: CompletionItemKind.Color),
'select-xs': DaisyuiComponent(label: 'select-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'select-sm': DaisyuiComponent(label: 'select-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'select-md': DaisyuiComponent(label: 'select-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'select-lg': DaisyuiComponent(label: 'select-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'select-xl': DaisyuiComponent(label: 'select-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'drawer': DaisyuiComponent(label: 'drawer', detail: 'The wrapper for sidebar and content', kind: CompletionItemKind.Constant),
'drawer-toggle': DaisyuiComponent(label: 'drawer-toggle', detail: 'The hidden checkbox that controls the state of drawer', kind: CompletionItemKind.Field),
'drawer-content': DaisyuiComponent(label: 'drawer-content', detail: 'Content part', kind: CompletionItemKind.Field),
'drawer-side': DaisyuiComponent(label: 'drawer-side', detail: 'Sidebar part', kind: CompletionItemKind.Field),
'drawer-overlay': DaisyuiComponent(label: 'drawer-overlay', detail: 'Label that covers the page when drawer is open', kind: CompletionItemKind.Field),
'drawer-end': DaisyuiComponent(label: 'drawer-end', detail: 'puts drawer to the other side', kind: CompletionItemKind.Value),
'drawer-open': DaisyuiComponent(label: 'drawer-open', detail: 'Forces the drawer to be open', kind: CompletionItemKind.Value),
'progress': DaisyuiComponent(label: 'progress', detail: 'For <progress> tag', kind: CompletionItemKind.Constant),
'progress-neutral': DaisyuiComponent(label: 'progress-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'progress-primary': DaisyuiComponent(label: 'progress-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'progress-secondary': DaisyuiComponent(label: 'progress-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'progress-accent': DaisyuiComponent(label: 'progress-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'progress-info': DaisyuiComponent(label: 'progress-info', detail: 'info color', kind: CompletionItemKind.Color),
'progress-success': DaisyuiComponent(label: 'progress-success', detail: 'success color', kind: CompletionItemKind.Color),
'progress-warning': DaisyuiComponent(label: 'progress-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'progress-error': DaisyuiComponent(label: 'progress-error', detail: 'error color', kind: CompletionItemKind.Color),
'fieldset': DaisyuiComponent(label: 'fieldset', detail: 'for the fieldset container', kind: CompletionItemKind.Constant),
'label': DaisyuiComponent(label: 'label', detail: 'label for inputs', kind: CompletionItemKind.Constant),
'fieldset-legend': DaisyuiComponent(label: 'fieldset-legend', detail: 'for the title of the fieldset', kind: CompletionItemKind.Field),
'alert': DaisyuiComponent(label: 'alert', detail: 'Container element', kind: CompletionItemKind.Constant),
'alert-outline': DaisyuiComponent(label: 'alert-outline', detail: 'outline style', kind: CompletionItemKind.Property),
'alert-dash': DaisyuiComponent(label: 'alert-dash', detail: 'dash outline style', kind: CompletionItemKind.Property),
'alert-soft': DaisyuiComponent(label: 'alert-soft', detail: 'soft style', kind: CompletionItemKind.Property),
'alert-info': DaisyuiComponent(label: 'alert-info', detail: 'info color', kind: CompletionItemKind.Color),
'alert-success': DaisyuiComponent(label: 'alert-success', detail: 'success color', kind: CompletionItemKind.Color),
'alert-warning': DaisyuiComponent(label: 'alert-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'alert-error': DaisyuiComponent(label: 'alert-error', detail: 'error color', kind: CompletionItemKind.Color),
'alert-vertical': DaisyuiComponent(label: 'alert-vertical', detail: 'Vertical layout, good for mobile', kind: CompletionItemKind.Value),
'alert-horizontal': DaisyuiComponent(label: 'alert-horizontal', detail: 'Horizontal layout, good for desktop', kind: CompletionItemKind.Value),
'divider': DaisyuiComponent(label: 'divider', detail: 'A divider line between two elements', kind: CompletionItemKind.Constant),
'divider-neutral': DaisyuiComponent(label: 'divider-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'divider-primary': DaisyuiComponent(label: 'divider-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'divider-secondary': DaisyuiComponent(label: 'divider-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'divider-accent': DaisyuiComponent(label: 'divider-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'divider-success': DaisyuiComponent(label: 'divider-success', detail: 'success color', kind: CompletionItemKind.Color),
'divider-warning': DaisyuiComponent(label: 'divider-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'divider-info': DaisyuiComponent(label: 'divider-info', detail: 'info color', kind: CompletionItemKind.Color),
'divider-error': DaisyuiComponent(label: 'divider-error', detail: 'error color', kind: CompletionItemKind.Color),
'divider-vertical': DaisyuiComponent(label: 'divider-vertical', detail: 'Divide vertical elements (on top of each other)', kind: CompletionItemKind.Value),
'divider-horizontal': DaisyuiComponent(label: 'divider-horizontal', detail: 'Divide horizontal elements (next to each other)', kind: CompletionItemKind.Value),
'divider-start': DaisyuiComponent(label: 'divider-start', detail: 'Pushes the divider text to the start', kind: CompletionItemKind.Value),
'divider-end': DaisyuiComponent(label: 'divider-end', detail: 'Pushes the divider text to the end', kind: CompletionItemKind.Value),
'hero': DaisyuiComponent(label: 'hero', detail: 'Hero container', kind: CompletionItemKind.Constant),
'hero-content': DaisyuiComponent(label: 'hero-content', detail: 'content part', kind: CompletionItemKind.Field),
'hero-overlay': DaisyuiComponent(label: 'hero-overlay', detail: 'Overlay that covers the background image', kind: CompletionItemKind.Field),
'link': DaisyuiComponent(label: 'link', detail: 'Adds underline', kind: CompletionItemKind.Constant),
'link-hover': DaisyuiComponent(label: 'link-hover', detail: 'Only shows underline on hover', kind: CompletionItemKind.Property),
'link-neutral': DaisyuiComponent(label: 'link-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'link-primary': DaisyuiComponent(label: 'link-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'link-secondary': DaisyuiComponent(label: 'link-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'link-accent': DaisyuiComponent(label: 'link-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'link-success': DaisyuiComponent(label: 'link-success', detail: 'success color', kind: CompletionItemKind.Color),
'link-info': DaisyuiComponent(label: 'link-info', detail: 'info color', kind: CompletionItemKind.Color),
'link-warning': DaisyuiComponent(label: 'link-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'link-error': DaisyuiComponent(label: 'link-error', detail: 'error color', kind: CompletionItemKind.Color),
'kbd': DaisyuiComponent(label: 'kbd', detail: 'Do show a keyboard key or a shortcut key', kind: CompletionItemKind.Constant),
'kbd-xs': DaisyuiComponent(label: 'kbd-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'kbd-sm': DaisyuiComponent(label: 'kbd-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'kbd-md': DaisyuiComponent(label: 'kbd-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'kbd-lg': DaisyuiComponent(label: 'kbd-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'kbd-xl': DaisyuiComponent(label: 'kbd-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'mockup-code': DaisyuiComponent(label: 'mockup-code', detail: 'Code terminal mockup', kind: CompletionItemKind.Constant),
'loading': DaisyuiComponent(label: 'loading', detail: 'Loading element', kind: CompletionItemKind.Constant),
'loading-spinner': DaisyuiComponent(label: 'loading-spinner', detail: 'spinner animation', kind: CompletionItemKind.Property),
'loading-dots': DaisyuiComponent(label: 'loading-dots', detail: 'dots animation', kind: CompletionItemKind.Property),
'loading-ring': DaisyuiComponent(label: 'loading-ring', detail: 'ring animation', kind: CompletionItemKind.Property),
'loading-ball': DaisyuiComponent(label: 'loading-ball', detail: 'ball animation', kind: CompletionItemKind.Property),
'loading-bars': DaisyuiComponent(label: 'loading-bars', detail: 'bars animation', kind: CompletionItemKind.Property),
'loading-infinity': DaisyuiComponent(label: 'loading-infinity', detail: 'infinity animation', kind: CompletionItemKind.Property),
'loading-xs': DaisyuiComponent(label: 'loading-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'loading-sm': DaisyuiComponent(label: 'loading-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'loading-md': DaisyuiComponent(label: 'loading-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'loading-lg': DaisyuiComponent(label: 'loading-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'loading-xl': DaisyuiComponent(label: 'loading-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'skeleton': DaisyuiComponent(label: 'skeleton', detail: 'A placeholder div with loading animation', kind: CompletionItemKind.Constant),
'swap': DaisyuiComponent(label: 'swap', detail: 'Swap container', kind: CompletionItemKind.Constant),
'swap-on': DaisyuiComponent(label: 'swap-on', detail: 'The child element that should be visible when checkbox is checked or when swap is active', kind: CompletionItemKind.Field),
'swap-off': DaisyuiComponent(label: 'swap-off', detail: 'The child element that should be visible when checkbox is not checked or when swap is not active', kind: CompletionItemKind.Field),
'swap-indeterminate': DaisyuiComponent(label: 'swap-indeterminate', detail: 'The child element that should be visible when checkbox is indeterminate', kind: CompletionItemKind.Field),
'swap-active': DaisyuiComponent(label: 'swap-active', detail: 'Activates the swap (no need for checkbox)', kind: CompletionItemKind.Value),
'swap-rotate': DaisyuiComponent(label: 'swap-rotate', detail: 'Adds rotate effect to swap', kind: CompletionItemKind.Property),
'swap-flip': DaisyuiComponent(label: 'swap-flip', detail: 'Adds flip effect to swap', kind: CompletionItemKind.Property),
'badge': DaisyuiComponent(label: 'badge', detail: 'Container element', kind: CompletionItemKind.Constant),
'badge-outline': DaisyuiComponent(label: 'badge-outline', detail: 'outline style', kind: CompletionItemKind.Property),
'badge-dash': DaisyuiComponent(label: 'badge-dash', detail: 'dash outline style', kind: CompletionItemKind.Property),
'badge-soft': DaisyuiComponent(label: 'badge-soft', detail: 'soft style', kind: CompletionItemKind.Property),
'badge-ghost': DaisyuiComponent(label: 'badge-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
'badge-neutral': DaisyuiComponent(label: 'badge-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'badge-primary': DaisyuiComponent(label: 'badge-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'badge-secondary': DaisyuiComponent(label: 'badge-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'badge-accent': DaisyuiComponent(label: 'badge-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'badge-info': DaisyuiComponent(label: 'badge-info', detail: 'info color', kind: CompletionItemKind.Color),
'badge-success': DaisyuiComponent(label: 'badge-success', detail: 'success color', kind: CompletionItemKind.Color),
'badge-warning': DaisyuiComponent(label: 'badge-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'badge-error': DaisyuiComponent(label: 'badge-error', detail: 'error color', kind: CompletionItemKind.Color),
'badge-xs': DaisyuiComponent(label: 'badge-xs', detail: 'extra small size', kind: CompletionItemKind.Unit),
'badge-sm': DaisyuiComponent(label: 'badge-sm', detail: 'small size', kind: CompletionItemKind.Unit),
'badge-md': DaisyuiComponent(label: 'badge-md', detail: 'medium size (default)', kind: CompletionItemKind.Unit),
'badge-lg': DaisyuiComponent(label: 'badge-lg', detail: 'large size', kind: CompletionItemKind.Unit),
'badge-xl': DaisyuiComponent(label: 'badge-xl', detail: 'extra large size', kind: CompletionItemKind.Unit),
'radio': DaisyuiComponent(label: 'radio', detail: 'For radio input', kind: CompletionItemKind.Constant),
'radio-neutral': DaisyuiComponent(label: 'radio-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'radio-primary': DaisyuiComponent(label: 'radio-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'radio-secondary': DaisyuiComponent(label: 'radio-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'radio-accent': DaisyuiComponent(label: 'radio-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'radio-success': DaisyuiComponent(label: 'radio-success', detail: 'success color', kind: CompletionItemKind.Color),
'radio-warning': DaisyuiComponent(label: 'radio-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'radio-info': DaisyuiComponent(label: 'radio-info', detail: 'info color', kind: CompletionItemKind.Color),
'radio-error': DaisyuiComponent(label: 'radio-error', detail: 'error color', kind: CompletionItemKind.Color),
'radio-xs': DaisyuiComponent(label: 'radio-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'radio-sm': DaisyuiComponent(label: 'radio-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'radio-md': DaisyuiComponent(label: 'radio-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'radio-lg': DaisyuiComponent(label: 'radio-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'radio-xl': DaisyuiComponent(label: 'radio-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'navbar': DaisyuiComponent(label: 'navbar', detail: 'Navigation bar', kind: CompletionItemKind.Constant),
'navbar-start': DaisyuiComponent(label: 'navbar-start', detail: 'For the div inside navbar, to fill 50% of width', kind: CompletionItemKind.Field),
'navbar-center': DaisyuiComponent(label: 'navbar-center', detail: 'For the div inside navbar, to be at center horizontally', kind: CompletionItemKind.Field),
'navbar-end': DaisyuiComponent(label: 'navbar-end', detail: 'For the div inside navbar, to fill second 50% of width', kind: CompletionItemKind.Field),
'collapse': DaisyuiComponent(label: 'collapse', detail: 'Collapse', kind: CompletionItemKind.Constant),
'collapse-title': DaisyuiComponent(label: 'collapse-title', detail: 'Title part', kind: CompletionItemKind.Field),
'collapse-content': DaisyuiComponent(label: 'collapse-content', detail: 'Content part', kind: CompletionItemKind.Field),
'collapse-arrow': DaisyuiComponent(label: 'collapse-arrow', detail: 'Adds arrow icon', kind: CompletionItemKind.Value),
'collapse-plus': DaisyuiComponent(label: 'collapse-plus', detail: 'Adds plus/minus icon', kind: CompletionItemKind.Value),
'collapse-open': DaisyuiComponent(label: 'collapse-open', detail: 'Force open', kind: CompletionItemKind.Value),
'collapse-close': DaisyuiComponent(label: 'collapse-close', detail: 'Force close', kind: CompletionItemKind.Value),
'textarea': DaisyuiComponent(label: 'textarea', detail: 'For <textarea> element', kind: CompletionItemKind.Constant),
'textarea-ghost': DaisyuiComponent(label: 'textarea-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
'textarea-neutral': DaisyuiComponent(label: 'textarea-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'textarea-primary': DaisyuiComponent(label: 'textarea-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'textarea-secondary': DaisyuiComponent(label: 'textarea-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'textarea-accent': DaisyuiComponent(label: 'textarea-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'textarea-info': DaisyuiComponent(label: 'textarea-info', detail: 'info color', kind: CompletionItemKind.Color),
'textarea-success': DaisyuiComponent(label: 'textarea-success', detail: 'success color', kind: CompletionItemKind.Color),
'textarea-warning': DaisyuiComponent(label: 'textarea-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'textarea-error': DaisyuiComponent(label: 'textarea-error', detail: 'error color', kind: CompletionItemKind.Color),
'textarea-xs': DaisyuiComponent(label: 'textarea-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'textarea-sm': DaisyuiComponent(label: 'textarea-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'textarea-md': DaisyuiComponent(label: 'textarea-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'textarea-lg': DaisyuiComponent(label: 'textarea-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'textarea-xl': DaisyuiComponent(label: 'textarea-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'btn': DaisyuiComponent(label: 'btn', detail: 'Button', kind: CompletionItemKind.Constant),
'btn-neutral': DaisyuiComponent(label: 'btn-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'btn-primary': DaisyuiComponent(label: 'btn-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'btn-secondary': DaisyuiComponent(label: 'btn-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'btn-accent': DaisyuiComponent(label: 'btn-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'btn-info': DaisyuiComponent(label: 'btn-info', detail: 'info color', kind: CompletionItemKind.Color),
'btn-success': DaisyuiComponent(label: 'btn-success', detail: 'success color', kind: CompletionItemKind.Color),
'btn-warning': DaisyuiComponent(label: 'btn-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'btn-error': DaisyuiComponent(label: 'btn-error', detail: 'error color', kind: CompletionItemKind.Color),
'btn-outline': DaisyuiComponent(label: 'btn-outline', detail: 'outline style', kind: CompletionItemKind.Property),
'btn-dash': DaisyuiComponent(label: 'btn-dash', detail: 'dash style', kind: CompletionItemKind.Property),
'btn-soft': DaisyuiComponent(label: 'btn-soft', detail: 'soft style', kind: CompletionItemKind.Property),
'btn-ghost': DaisyuiComponent(label: 'btn-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
'btn-link': DaisyuiComponent(label: 'btn-link', detail: 'looks like a link', kind: CompletionItemKind.Property),
'btn-active': DaisyuiComponent(label: 'btn-active', detail: 'looks active', kind: CompletionItemKind.Value),
'btn-disabled': DaisyuiComponent(label: 'btn-disabled', detail: 'looks disabled', kind: CompletionItemKind.Value),
'btn-xs': DaisyuiComponent(label: 'btn-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'btn-sm': DaisyuiComponent(label: 'btn-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'btn-md': DaisyuiComponent(label: 'btn-md', detail: 'Medium size (default)', kind: CompletionItemKind.Unit),
'btn-lg': DaisyuiComponent(label: 'btn-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'btn-xl': DaisyuiComponent(label: 'btn-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'btn-wide': DaisyuiComponent(label: 'btn-wide', detail: 'more horizontal padding', kind: CompletionItemKind.Value),
'btn-block': DaisyuiComponent(label: 'btn-block', detail: 'Full width', kind: CompletionItemKind.Value),
'btn-square': DaisyuiComponent(label: 'btn-square', detail: '1:1 ratio', kind: CompletionItemKind.Value),
'btn-circle': DaisyuiComponent(label: 'btn-circle', detail: '1:1 ratio with rounded corners', kind: CompletionItemKind.Value),
'chat': DaisyuiComponent(label: 'chat', detail: 'Container for one line of conversation and its data', kind: CompletionItemKind.Constant),
'chat-image': DaisyuiComponent(label: 'chat-image', detail: 'Author image', kind: CompletionItemKind.Field),
'chat-header': DaisyuiComponent(label: 'chat-header', detail: 'Text above the chat bubble', kind: CompletionItemKind.Field),
'chat-footer': DaisyuiComponent(label: 'chat-footer', detail: 'Text below the chat bubble', kind: CompletionItemKind.Field),
'chat-bubble': DaisyuiComponent(label: 'chat-bubble', detail: 'Chat bubble', kind: CompletionItemKind.Field),
'chat-start': DaisyuiComponent(label: 'chat-start', detail: 'Aligns chat to start horizontally (required)', kind: CompletionItemKind.Value),
'chat-end': DaisyuiComponent(label: 'chat-end', detail: 'Aligns chat to end horizontally (required)', kind: CompletionItemKind.Value),
'chat-bubble-neutral': DaisyuiComponent(label: 'chat-bubble-neutral', detail: 'neutral color for chat-bubble', kind: CompletionItemKind.Color),
'chat-bubble-primary': DaisyuiComponent(label: 'chat-bubble-primary', detail: 'primary color for chat-bubble', kind: CompletionItemKind.Color),
'chat-bubble-secondary': DaisyuiComponent(label: 'chat-bubble-secondary', detail: 'secondary color for chat-bubble', kind: CompletionItemKind.Color),
'chat-bubble-accent': DaisyuiComponent(label: 'chat-bubble-accent', detail: 'accent color for chat-bubble', kind: CompletionItemKind.Color),
'chat-bubble-info': DaisyuiComponent(label: 'chat-bubble-info', detail: 'info color for chat-bubble', kind: CompletionItemKind.Color),
'chat-bubble-success': DaisyuiComponent(label: 'chat-bubble-success', detail: 'success color for chat-bubble', kind: CompletionItemKind.Color),
'chat-bubble-warning': DaisyuiComponent(label: 'chat-bubble-warning', detail: 'warning color for chat-bubble', kind: CompletionItemKind.Color),
'chat-bubble-error': DaisyuiComponent(label: 'chat-bubble-error', detail: 'error color for chat-bubble', kind: CompletionItemKind.Color),
'tabs': DaisyuiComponent(label: 'tabs', detail: 'Container of multiple tab items', kind: CompletionItemKind.Constant),
'tab': DaisyuiComponent(label: 'tab', detail: 'A single tab button (can be button, link, div, radio input, etc)', kind: CompletionItemKind.Field),
'tab-content': DaisyuiComponent(label: 'tab-content', detail: 'Tab content that comes immediately after a tab', kind: CompletionItemKind.Field),
'tabs-box': DaisyuiComponent(label: 'tabs-box', detail: 'box style', kind: CompletionItemKind.Property),
'tabs-border': DaisyuiComponent(label: 'tabs-border', detail: 'bottom border style', kind: CompletionItemKind.Property),
'tabs-lift': DaisyuiComponent(label: 'tabs-lift', detail: 'lift style', kind: CompletionItemKind.Property),
'tab-active': DaisyuiComponent(label: 'tab-active', detail: 'Makes a single tab look active', kind: CompletionItemKind.Value),
'tab-disabled': DaisyuiComponent(label: 'tab-disabled', detail: 'Makes a single tab look disabled', kind: CompletionItemKind.Value),
'tabs-top': DaisyuiComponent(label: 'tabs-top', detail: 'Puts tab buttons on top of the tab-content (default)', kind: CompletionItemKind.Value),
'tabs-bottom': DaisyuiComponent(label: 'tabs-bottom', detail: 'Puts tabs on under the tab-content', kind: CompletionItemKind.Value),
'tabs-xs': DaisyuiComponent(label: 'tabs-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'tabs-sm': DaisyuiComponent(label: 'tabs-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'tabs-md': DaisyuiComponent(label: 'tabs-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'tabs-lg': DaisyuiComponent(label: 'tabs-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'tabs-xl': DaisyuiComponent(label: 'tabs-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'stack': DaisyuiComponent(label: 'stack', detail: 'Puts the children elements on top of each other', kind: CompletionItemKind.Constant),
'stack-top': DaisyuiComponent(label: 'stack-top', detail: 'Aligns the children elements to the top', kind: CompletionItemKind.Value),
'stack-bottom': DaisyuiComponent(label: 'stack-bottom', detail: 'Aligns the children elements to the bottom', kind: CompletionItemKind.Value),
'stack-start': DaisyuiComponent(label: 'stack-start', detail: 'Aligns the children elements to the start (horizontally)', kind: CompletionItemKind.Value),
'stack-end': DaisyuiComponent(label: 'stack-end', detail: 'Aligns the children elements to the end (horizontally)', kind: CompletionItemKind.Value),
'join': DaisyuiComponent(label: 'join', detail: 'For grouping multiple items', kind: CompletionItemKind.Constant),
'join-item': DaisyuiComponent(label: 'join-item', detail: 'Item inside join. Can be a button, input, etc.', kind: CompletionItemKind.Constant),
'join-vertical': DaisyuiComponent(label: 'join-vertical', detail: 'Show items vertically', kind: CompletionItemKind.Value),
'join-horizontal': DaisyuiComponent(label: 'join-horizontal', detail: 'Show items horizontally', kind: CompletionItemKind.Value),
'range': DaisyuiComponent(label: 'range', detail: 'For <input type="range"> tag', kind: CompletionItemKind.Constant),
'range-neutral': DaisyuiComponent(label: 'range-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'range-primary': DaisyuiComponent(label: 'range-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'range-secondary': DaisyuiComponent(label: 'range-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'range-accent': DaisyuiComponent(label: 'range-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'range-success': DaisyuiComponent(label: 'range-success', detail: 'success color', kind: CompletionItemKind.Color),
'range-warning': DaisyuiComponent(label: 'range-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'range-info': DaisyuiComponent(label: 'range-info', detail: 'info color', kind: CompletionItemKind.Color),
'range-error': DaisyuiComponent(label: 'range-error', detail: 'error color', kind: CompletionItemKind.Color),
'range-xs': DaisyuiComponent(label: 'range-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'range-sm': DaisyuiComponent(label: 'range-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'range-md': DaisyuiComponent(label: 'range-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'range-lg': DaisyuiComponent(label: 'range-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'range-xl': DaisyuiComponent(label: 'range-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'checkbox': DaisyuiComponent(label: 'checkbox', detail: 'Checkbox', kind: CompletionItemKind.Constant),
'checkbox-primary': DaisyuiComponent(label: 'checkbox-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'checkbox-secondary': DaisyuiComponent(label: 'checkbox-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'checkbox-accent': DaisyuiComponent(label: 'checkbox-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'checkbox-neutral': DaisyuiComponent(label: 'checkbox-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'checkbox-success': DaisyuiComponent(label: 'checkbox-success', detail: 'success color', kind: CompletionItemKind.Color),
'checkbox-warning': DaisyuiComponent(label: 'checkbox-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'checkbox-info': DaisyuiComponent(label: 'checkbox-info', detail: 'info color', kind: CompletionItemKind.Color),
'checkbox-error': DaisyuiComponent(label: 'checkbox-error', detail: 'error color', kind: CompletionItemKind.Color),
'checkbox-xs': DaisyuiComponent(label: 'checkbox-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'checkbox-sm': DaisyuiComponent(label: 'checkbox-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'checkbox-md': DaisyuiComponent(label: 'checkbox-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'checkbox-lg': DaisyuiComponent(label: 'checkbox-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'checkbox-xl': DaisyuiComponent(label: 'checkbox-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'radial-progress': DaisyuiComponent(label: 'radial-progress', detail: 'Shows a radial progress', kind: CompletionItemKind.Constant),
'toast': DaisyuiComponent(label: 'toast', detail: 'Container element that sticks to the corner of page', kind: CompletionItemKind.Constant),
'toast-start': DaisyuiComponent(label: 'toast-start', detail: 'align horizontally to the left', kind: CompletionItemKind.Value),
'toast-center': DaisyuiComponent(label: 'toast-center', detail: 'align horizontally to the center', kind: CompletionItemKind.Value),
'toast-end': DaisyuiComponent(label: 'toast-end', detail: 'align horizontally to the right', kind: CompletionItemKind.Value),
'toast-top': DaisyuiComponent(label: 'toast-top', detail: 'align vertically to top', kind: CompletionItemKind.Value),
'toast-middle': DaisyuiComponent(label: 'toast-middle', detail: 'align vertically to middle', kind: CompletionItemKind.Value),
'toast-bottom': DaisyuiComponent(label: 'toast-bottom', detail: 'align vertically to bottom', kind: CompletionItemKind.Value),
'steps': DaisyuiComponent(label: 'steps', detail: 'Container of multiple step nodes', kind: CompletionItemKind.Constant),
'step': DaisyuiComponent(label: 'step', detail: 'A single step node', kind: CompletionItemKind.Field),
'step-icon': DaisyuiComponent(label: 'step-icon', detail: 'For custom icon inside step', kind: CompletionItemKind.Field),
'step-neutral': DaisyuiComponent(label: 'step-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'step-primary': DaisyuiComponent(label: 'step-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'step-secondary': DaisyuiComponent(label: 'step-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'step-accent': DaisyuiComponent(label: 'step-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'step-info': DaisyuiComponent(label: 'step-info', detail: 'info color', kind: CompletionItemKind.Color),
'step-success': DaisyuiComponent(label: 'step-success', detail: 'success color', kind: CompletionItemKind.Color),
'step-warning': DaisyuiComponent(label: 'step-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'step-error': DaisyuiComponent(label: 'step-error', detail: 'error color', kind: CompletionItemKind.Color),
'steps-vertical': DaisyuiComponent(label: 'steps-vertical', detail: 'Makes steps vertical (default)', kind: CompletionItemKind.Value),
'steps-horizontal': DaisyuiComponent(label: 'steps-horizontal', detail: 'Makes steps horizontal', kind: CompletionItemKind.Value),
'cally': DaisyuiComponent(label: 'cally', detail: 'for Cally web component', kind: CompletionItemKind.Constant),
'pika-single': DaisyuiComponent(label: 'pika-single', detail: 'for the input field that opens Pikaday calendar', kind: CompletionItemKind.Constant),
'react-day-picker': DaisyuiComponent(label: 'react-day-picker', detail: 'for the DayPicker component', kind: CompletionItemKind.Constant),
'toggle': DaisyuiComponent(label: 'toggle', detail: 'For <input type="checkbox">', kind: CompletionItemKind.Constant),
'toggle-primary': DaisyuiComponent(label: 'toggle-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'toggle-secondary': DaisyuiComponent(label: 'toggle-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'toggle-accent': DaisyuiComponent(label: 'toggle-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'toggle-neutral': DaisyuiComponent(label: 'toggle-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'toggle-success': DaisyuiComponent(label: 'toggle-success', detail: 'success color', kind: CompletionItemKind.Color),
'toggle-warning': DaisyuiComponent(label: 'toggle-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'toggle-info': DaisyuiComponent(label: 'toggle-info', detail: 'info color', kind: CompletionItemKind.Color),
'toggle-error': DaisyuiComponent(label: 'toggle-error', detail: 'error color', kind: CompletionItemKind.Color),
'toggle-xs': DaisyuiComponent(label: 'toggle-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'toggle-sm': DaisyuiComponent(label: 'toggle-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'toggle-md': DaisyuiComponent(label: 'toggle-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'toggle-lg': DaisyuiComponent(label: 'toggle-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'toggle-xl': DaisyuiComponent(label: 'toggle-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'mockup-phone': DaisyuiComponent(label: 'mockup-phone', detail: 'Phone mockup', kind: CompletionItemKind.Constant),
'mockup-phone-camera': DaisyuiComponent(label: 'mockup-phone-camera', detail: 'Camera part', kind: CompletionItemKind.Field),
'mockup-phone-display': DaisyuiComponent(label: 'mockup-phone-display', detail: 'Display part', kind: CompletionItemKind.Field),
'mockup-window': DaisyuiComponent(label: 'mockup-window', detail: 'OS window mockup', kind: CompletionItemKind.Constant),
'carousel': DaisyuiComponent(label: 'carousel', detail: 'Carousel container', kind: CompletionItemKind.Constant),
'carousel-item': DaisyuiComponent(label: 'carousel-item', detail: 'Carousel item', kind: CompletionItemKind.Field),
'carousel-start': DaisyuiComponent(label: 'carousel-start', detail: 'Snap elements to start', kind: CompletionItemKind.Value),
'carousel-center': DaisyuiComponent(label: 'carousel-center', detail: 'Snap elements to center', kind: CompletionItemKind.Value),
'carousel-end': DaisyuiComponent(label: 'carousel-end', detail: 'Snap elements to end', kind: CompletionItemKind.Value),
'carousel-horizontal': DaisyuiComponent(label: 'carousel-horizontal', detail: 'Horizontal layout (default)', kind: CompletionItemKind.Value),
'carousel-vertical': DaisyuiComponent(label: 'carousel-vertical', detail: 'Vertical layout', kind: CompletionItemKind.Value),
'list': DaisyuiComponent(label: 'list', detail: 'A vertical flex layout to include list rows', kind: CompletionItemKind.Constant),
'list-row': DaisyuiComponent(label: 'list-row', detail: 'The item inside list. A horizontal grid layout to include data', kind: CompletionItemKind.Constant),
'list-col-wrap': DaisyuiComponent(label: 'list-col-wrap', detail: 'For one of direct children of list-row to push it to the next line', kind: CompletionItemKind.Value),
'list-col-grow': DaisyuiComponent(label: 'list-col-grow', detail: 'For one of direct children of list-row to make it fill the remaining space', kind: CompletionItemKind.Value),
'tooltip': DaisyuiComponent(label: 'tooltip', detail: 'Container element', kind: CompletionItemKind.Constant),
'tooltip-content': DaisyuiComponent(label: 'tooltip-content', detail: 'Optional. Setting a div as the content of the tooltip instead of the `data-tip` text', kind: CompletionItemKind.Field),
'tooltip-top': DaisyuiComponent(label: 'tooltip-top', detail: 'Put tooltip on top', kind: CompletionItemKind.Value),
'tooltip-bottom': DaisyuiComponent(label: 'tooltip-bottom', detail: 'Put tooltip on bottom', kind: CompletionItemKind.Value),
'tooltip-left': DaisyuiComponent(label: 'tooltip-left', detail: 'Put tooltip on left', kind: CompletionItemKind.Value),
'tooltip-right': DaisyuiComponent(label: 'tooltip-right', detail: 'Put tooltip on right', kind: CompletionItemKind.Value),
'tooltip-open': DaisyuiComponent(label: 'tooltip-open', detail: 'Force open tooltip', kind: CompletionItemKind.Value),
'tooltip-neutral': DaisyuiComponent(label: 'tooltip-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'tooltip-primary': DaisyuiComponent(label: 'tooltip-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'tooltip-secondary': DaisyuiComponent(label: 'tooltip-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'tooltip-accent': DaisyuiComponent(label: 'tooltip-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'tooltip-info': DaisyuiComponent(label: 'tooltip-info', detail: 'info color', kind: CompletionItemKind.Color),
'tooltip-success': DaisyuiComponent(label: 'tooltip-success', detail: 'success color', kind: CompletionItemKind.Color),
'tooltip-warning': DaisyuiComponent(label: 'tooltip-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'tooltip-error': DaisyuiComponent(label: 'tooltip-error', detail: 'error color', kind: CompletionItemKind.Color),
'dock': DaisyuiComponent(label: 'dock', detail: 'Dock', kind: CompletionItemKind.Constant),
'dock-label': DaisyuiComponent(label: 'dock-label', detail: 'Text label for Dock Item', kind: CompletionItemKind.Field),
'dock-active': DaisyuiComponent(label: 'dock-active', detail: 'Makes the Dock Item look active', kind: CompletionItemKind.Value),
'dock-xs': DaisyuiComponent(label: 'dock-xs', detail: 'Extra Small Dock', kind: CompletionItemKind.Unit),
'dock-sm': DaisyuiComponent(label: 'dock-sm', detail: 'Small Dock', kind: CompletionItemKind.Unit),
'dock-md': DaisyuiComponent(label: 'dock-md', detail: 'Medium Dock', kind: CompletionItemKind.Unit),
'dock-lg': DaisyuiComponent(label: 'dock-lg', detail: 'Large Dock', kind: CompletionItemKind.Unit),
'dock-xl': DaisyuiComponent(label: 'dock-xl', detail: 'Extra Large Dock', kind: CompletionItemKind.Unit),
'modal': DaisyuiComponent(label: 'modal', detail: 'Modal', kind: CompletionItemKind.Constant),
'modal-box': DaisyuiComponent(label: 'modal-box', detail: 'The content part', kind: CompletionItemKind.Field),
'modal-action': DaisyuiComponent(label: 'modal-action', detail: 'Actions part (buttons, etc.)', kind: CompletionItemKind.Field),
'modal-backdrop': DaisyuiComponent(label: 'modal-backdrop', detail: 'Label that covers the page when modal is open so we can close the modal by clicking outside', kind: CompletionItemKind.Field),
'modal-toggle': DaisyuiComponent(label: 'modal-toggle', detail: 'Hidden checkbox that controls the state of modal', kind: CompletionItemKind.Field),
'modal-open': DaisyuiComponent(label: 'modal-open', detail: 'Keeps the modal open (you can add this class using JS)', kind: CompletionItemKind.Value),
'modal-top': DaisyuiComponent(label: 'modal-top', detail: 'Moves the modal to top', kind: CompletionItemKind.Value),
'modal-middle': DaisyuiComponent(label: 'modal-middle', detail: 'Moves the modal to middle', kind: CompletionItemKind.Value),
'modal-bottom': DaisyuiComponent(label: 'modal-bottom', detail: 'Moves the modal to bottom', kind: CompletionItemKind.Value),
'modal-start': DaisyuiComponent(label: 'modal-start', detail: 'Moves the modal to start horizontally', kind: CompletionItemKind.Value),
'modal-end': DaisyuiComponent(label: 'modal-end', detail: 'Moves the modal to end horizontally', kind: CompletionItemKind.Value),
'menu': DaisyuiComponent(label: 'menu', detail: 'For <ul> tag', kind: CompletionItemKind.Constant),
'menu-title': DaisyuiComponent(label: 'menu-title', detail: 'styles a <li> as title', kind: CompletionItemKind.Field),
'menu-dropdown': DaisyuiComponent(label: 'menu-dropdown', detail: 'For the collapsible <ul> if you want to show it using JS', kind: CompletionItemKind.Field),
'menu-dropdown-toggle': DaisyuiComponent(label: 'menu-dropdown-toggle', detail: 'For the toggle to show/hide the menu-dropdown using JS', kind: CompletionItemKind.Field),
'menu-disabled': DaisyuiComponent(label: 'menu-disabled', detail: 'For disabling a <li>', kind: CompletionItemKind.Value),
'menu-active': DaisyuiComponent(label: 'menu-active', detail: 'For the element inside <li> to look active', kind: CompletionItemKind.Value),
'menu-focus': DaisyuiComponent(label: 'menu-focus', detail: 'For the element inside <li> to look focused', kind: CompletionItemKind.Value),
'menu-dropdown-show': DaisyuiComponent(label: 'menu-dropdown-show', detail: 'Shows the menu-dropdown-toggle and menu-dropdown collapsible submenu using JS', kind: CompletionItemKind.Value),
'menu-xs': DaisyuiComponent(label: 'menu-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'menu-sm': DaisyuiComponent(label: 'menu-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'menu-md': DaisyuiComponent(label: 'menu-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'menu-lg': DaisyuiComponent(label: 'menu-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'menu-xl': DaisyuiComponent(label: 'menu-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'menu-vertical': DaisyuiComponent(label: 'menu-vertical', detail: 'Vertical menu (default)', kind: CompletionItemKind.Value),
'menu-horizontal': DaisyuiComponent(label: 'menu-horizontal', detail: 'Horizontal menu', kind: CompletionItemKind.Value),
'table': DaisyuiComponent(label: 'table', detail: 'For <table> tag', kind: CompletionItemKind.Constant),
'table-zebra': DaisyuiComponent(label: 'table-zebra', detail: 'For <table> to show zebra stripe rows', kind: CompletionItemKind.Value),
'table-pin-rows': DaisyuiComponent(label: 'table-pin-rows', detail: 'For <table> to make all the rows inside <thead> and <tfoot> sticky', kind: CompletionItemKind.Value),
'table-pin-cols': DaisyuiComponent(label: 'table-pin-cols', detail: 'For <table> to make all the <th> columns sticky', kind: CompletionItemKind.Value),
'table-xs': DaisyuiComponent(label: 'table-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'table-sm': DaisyuiComponent(label: 'table-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'table-md': DaisyuiComponent(label: 'table-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'table-lg': DaisyuiComponent(label: 'table-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'table-xl': DaisyuiComponent(label: 'table-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'validator': DaisyuiComponent(label: 'validator', detail: 'For input, select, textarea', kind: CompletionItemKind.Constant),
'validator-hint': DaisyuiComponent(label: 'validator-hint', detail: "for the hint text that appears after the input if it's invalid", kind: CompletionItemKind.Field),
'card': DaisyuiComponent(label: 'card', detail: 'Card', kind: CompletionItemKind.Constant),
'card-title': DaisyuiComponent(label: 'card-title', detail: 'Title part', kind: CompletionItemKind.Field),
'card-body': DaisyuiComponent(label: 'card-body', detail: 'Body part (content)', kind: CompletionItemKind.Field),
'card-actions': DaisyuiComponent(label: 'card-actions', detail: 'Actions part (buttons, etc.)', kind: CompletionItemKind.Field),
'card-border': DaisyuiComponent(label: 'card-border', detail: 'Adds border to <card>', kind: CompletionItemKind.Property),
'card-dash': DaisyuiComponent(label: 'card-dash', detail: 'dash style', kind: CompletionItemKind.Property),
'card-side': DaisyuiComponent(label: 'card-side', detail: 'The image in <figure> will be on to the side', kind: CompletionItemKind.Value),
'image-full': DaisyuiComponent(label: 'image-full', detail: 'The image in <figure> element will be the background', kind: CompletionItemKind.Value),
'card-xs': DaisyuiComponent(label: 'card-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'card-sm': DaisyuiComponent(label: 'card-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'card-md': DaisyuiComponent(label: 'card-md', detail: 'Medium size (default)', kind: CompletionItemKind.Unit),
'card-lg': DaisyuiComponent(label: 'card-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'card-xl': DaisyuiComponent(label: 'card-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'breadcrumbs': DaisyuiComponent(label: 'breadcrumbs', detail: 'Wrapper around a <ul>', kind: CompletionItemKind.Constant),
'countdown': DaisyuiComponent(label: 'countdown', detail: 'Countdown wrapper', kind: CompletionItemKind.Constant),
'floating-label': DaisyuiComponent(label: 'floating-label', detail: 'For the parent of an input field (or select) and a span that floats above the input field when the field is focused', kind: CompletionItemKind.Constant),
'rating': DaisyuiComponent(label: 'rating', detail: 'For a div containing radio inputs', kind: CompletionItemKind.Constant),
'rating-half': DaisyuiComponent(label: 'rating-half', detail: 'To shows half of the shapes. Useful for half star ratings', kind: CompletionItemKind.Value),
'rating-hidden': DaisyuiComponent(label: 'rating-hidden', detail: 'For the first radio to make it hidden so user can clear the rating', kind: CompletionItemKind.Value),
'rating-xs': DaisyuiComponent(label: 'rating-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'rating-sm': DaisyuiComponent(label: 'rating-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'rating-md': DaisyuiComponent(label: 'rating-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'rating-lg': DaisyuiComponent(label: 'rating-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'rating-xl': DaisyuiComponent(label: 'rating-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'avatar': DaisyuiComponent(label: 'avatar', detail: 'Avatar', kind: CompletionItemKind.Constant),
'avatar-group': DaisyuiComponent(label: 'avatar-group', detail: 'Container for multiple avatars', kind: CompletionItemKind.Constant),
'avatar-online': DaisyuiComponent(label: 'avatar-online', detail: 'shows a green dot as online indicator', kind: CompletionItemKind.Value),
'avatar-offline': DaisyuiComponent(label: 'avatar-offline', detail: 'shows a gray dot as offline indicator', kind: CompletionItemKind.Value),
'avatar-placeholder': DaisyuiComponent(label: 'avatar-placeholder', detail: 'To show letters as avatar placeholder', kind: CompletionItemKind.Value),
'mask': DaisyuiComponent(label: 'mask', detail: 'Masks the content with shape', kind: CompletionItemKind.Constant),
'mask-squircle': DaisyuiComponent(label: 'mask-squircle', detail: 'squircle', kind: CompletionItemKind.Property),
'mask-heart': DaisyuiComponent(label: 'mask-heart', detail: 'heart', kind: CompletionItemKind.Property),
'mask-hexagon': DaisyuiComponent(label: 'mask-hexagon', detail: 'hexagon vertical', kind: CompletionItemKind.Property),
'mask-hexagon-2': DaisyuiComponent(label: 'mask-hexagon-2', detail: 'hexagon horizontal', kind: CompletionItemKind.Property),
'mask-decagon': DaisyuiComponent(label: 'mask-decagon', detail: 'decagon', kind: CompletionItemKind.Property),
'mask-pentagon': DaisyuiComponent(label: 'mask-pentagon', detail: 'pentagon', kind: CompletionItemKind.Property),
'mask-diamond': DaisyuiComponent(label: 'mask-diamond', detail: 'diamond', kind: CompletionItemKind.Property),
'mask-square': DaisyuiComponent(label: 'mask-square', detail: 'square', kind: CompletionItemKind.Property),
'mask-circle': DaisyuiComponent(label: 'mask-circle', detail: 'circle', kind: CompletionItemKind.Property),
'mask-star': DaisyuiComponent(label: 'mask-star', detail: 'star', kind: CompletionItemKind.Property),
'mask-star-2': DaisyuiComponent(label: 'mask-star-2', detail: 'star (bold)', kind: CompletionItemKind.Property),
'mask-triangle': DaisyuiComponent(label: 'mask-triangle', detail: 'triangle pointing top', kind: CompletionItemKind.Property),
'mask-triangle-2': DaisyuiComponent(label: 'mask-triangle-2', detail: 'triangle pointing down', kind: CompletionItemKind.Property),
'mask-triangle-3': DaisyuiComponent(label: 'mask-triangle-3', detail: 'triangle pointing left', kind: CompletionItemKind.Property),
'mask-triangle-4': DaisyuiComponent(label: 'mask-triangle-4', detail: 'triangle pointing right', kind: CompletionItemKind.Property),
'mask-half-1': DaisyuiComponent(label: 'mask-half-1', detail: 'Crops only the first half of mask', kind: CompletionItemKind.Value),
'mask-half-2': DaisyuiComponent(label: 'mask-half-2', detail: 'Crops only the second half of mask', kind: CompletionItemKind.Value),
'dropdown': DaisyuiComponent(label: 'dropdown', detail: 'Dropdown container', kind: CompletionItemKind.Constant),
'dropdown-content': DaisyuiComponent(label: 'dropdown-content', detail: 'Content part', kind: CompletionItemKind.Field),
'dropdown-start': DaisyuiComponent(label: 'dropdown-start', detail: 'Align horizontally to start of button', kind: CompletionItemKind.Value),
'dropdown-center': DaisyuiComponent(label: 'dropdown-center', detail: 'Align horizontally to center of button', kind: CompletionItemKind.Value),
'dropdown-end': DaisyuiComponent(label: 'dropdown-end', detail: 'Align horizontally to end of button', kind: CompletionItemKind.Value),
'dropdown-top': DaisyuiComponent(label: 'dropdown-top', detail: 'Open from top', kind: CompletionItemKind.Value),
'dropdown-bottom': DaisyuiComponent(label: 'dropdown-bottom', detail: 'Open from bottom', kind: CompletionItemKind.Value),
'dropdown-left': DaisyuiComponent(label: 'dropdown-left', detail: 'Open from left', kind: CompletionItemKind.Value),
'dropdown-right': DaisyuiComponent(label: 'dropdown-right', detail: 'Open from right', kind: CompletionItemKind.Value),
'dropdown-hover': DaisyuiComponent(label: 'dropdown-hover', detail: 'Opens on hover too', kind: CompletionItemKind.Value),
'dropdown-open': DaisyuiComponent(label: 'dropdown-open', detail: 'Force open', kind: CompletionItemKind.Value),
'indicator': DaisyuiComponent(label: 'indicator', detail: 'Container element', kind: CompletionItemKind.Constant),
'indicator-item': DaisyuiComponent(label: 'indicator-item', detail: 'will be placed on the corner of sibling', kind: CompletionItemKind.Field),
'indicator-start': DaisyuiComponent(label: 'indicator-start', detail: 'align horizontally to the start', kind: CompletionItemKind.Value),
'indicator-center': DaisyuiComponent(label: 'indicator-center', detail: 'align horizontally to the center', kind: CompletionItemKind.Value),
'indicator-end': DaisyuiComponent(label: 'indicator-end', detail: 'align horizontally to the end', kind: CompletionItemKind.Value),
'indicator-top': DaisyuiComponent(label: 'indicator-top', detail: 'align vertically to top', kind: CompletionItemKind.Value),
'indicator-middle': DaisyuiComponent(label: 'indicator-middle', detail: 'align vertically to middle', kind: CompletionItemKind.Value),
'indicator-bottom': DaisyuiComponent(label: 'indicator-bottom', detail: 'align vertically to bottom', kind: CompletionItemKind.Value),
'timeline': DaisyuiComponent(label: 'timeline', detail: 'Timeline container', kind: CompletionItemKind.Constant),
'timeline-start': DaisyuiComponent(label: 'timeline-start', detail: 'The content inside <li> that will be at the start direction', kind: CompletionItemKind.Field),
'timeline-middle': DaisyuiComponent(label: 'timeline-middle', detail: 'The content inside <li> that will be at the middle', kind: CompletionItemKind.Field),
'timeline-end': DaisyuiComponent(label: 'timeline-end', detail: 'The content inside <li> that will be at the end direction', kind: CompletionItemKind.Field),
'timeline-snap-icon': DaisyuiComponent(label: 'timeline-snap-icon', detail: 'snaps the icon to the start instead of middle', kind: CompletionItemKind.Value),
'timeline-box': DaisyuiComponent(label: 'timeline-box', detail: 'Applies a box style to timeline-start or timeline-end', kind: CompletionItemKind.Value),
'timeline-compact': DaisyuiComponent(label: 'timeline-compact', detail: 'forces all items on one side', kind: CompletionItemKind.Value),
'timeline-horizontal': DaisyuiComponent(label: 'timeline-horizontal', detail: 'horizontal layout (default)', kind: CompletionItemKind.Value),
'timeline-vertical': DaisyuiComponent(label: 'timeline-vertical', detail: 'vertical layout', kind: CompletionItemKind.Value),
'input': DaisyuiComponent(label: 'input', detail: 'For <input type="text"> tag or a wrapper of <input type="text"> tag', kind: CompletionItemKind.Constant),
'input-ghost': DaisyuiComponent(label: 'input-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
'input-neutral': DaisyuiComponent(label: 'input-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'input-primary': DaisyuiComponent(label: 'input-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'input-secondary': DaisyuiComponent(label: 'input-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'input-accent': DaisyuiComponent(label: 'input-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'input-info': DaisyuiComponent(label: 'input-info', detail: 'info color', kind: CompletionItemKind.Color),
'input-success': DaisyuiComponent(label: 'input-success', detail: 'success color', kind: CompletionItemKind.Color),
'input-warning': DaisyuiComponent(label: 'input-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'input-error': DaisyuiComponent(label: 'input-error', detail: 'error color', kind: CompletionItemKind.Color),
'input-xs': DaisyuiComponent(label: 'input-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'input-sm': DaisyuiComponent(label: 'input-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'input-md': DaisyuiComponent(label: 'input-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'input-lg': DaisyuiComponent(label: 'input-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'input-xl': DaisyuiComponent(label: 'input-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'footer': DaisyuiComponent(label: 'footer', detail: 'Footer', kind: CompletionItemKind.Constant),
'footer-title': DaisyuiComponent(label: 'footer-title', detail: 'Title of a footer column', kind: CompletionItemKind.Field),
'footer-center': DaisyuiComponent(label: 'footer-center', detail: 'Aligns footer content to center', kind: CompletionItemKind.Value),
'footer-horizontal': DaisyuiComponent(label: 'footer-horizontal', detail: 'Puts footer columns next to each other horizontally', kind: CompletionItemKind.Value),
'footer-vertical': DaisyuiComponent(label: 'footer-vertical', detail: 'Puts footer columns under each other vertically', kind: CompletionItemKind.Value),
'mockup-browser': DaisyuiComponent(label: 'mockup-browser', detail: 'Browser mockup', kind: CompletionItemKind.Constant),
'mockup-browser-toolbar': DaisyuiComponent(label: 'mockup-browser-toolbar', detail: 'Toolbar part which can include addressbar, etc', kind: CompletionItemKind.Field),
'status': DaisyuiComponent(label: 'status', detail: 'Status icon', kind: CompletionItemKind.Constant),
'status-neutral': DaisyuiComponent(label: 'status-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'status-primary': DaisyuiComponent(label: 'status-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'status-secondary': DaisyuiComponent(label: 'status-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'status-accent': DaisyuiComponent(label: 'status-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'status-info': DaisyuiComponent(label: 'status-info', detail: 'info color', kind: CompletionItemKind.Color),
'status-success': DaisyuiComponent(label: 'status-success', detail: 'success color', kind: CompletionItemKind.Color),
'status-warning': DaisyuiComponent(label: 'status-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'status-error': DaisyuiComponent(label: 'status-error', detail: 'error color', kind: CompletionItemKind.Color),
'status-xs': DaisyuiComponent(label: 'status-xs', detail: 'extra small size', kind: CompletionItemKind.Unit),
'status-sm': DaisyuiComponent(label: 'status-sm', detail: 'small size', kind: CompletionItemKind.Unit),
'status-md': DaisyuiComponent(label: 'status-md', detail: 'medium size', kind: CompletionItemKind.Unit),
'status-lg': DaisyuiComponent(label: 'status-lg', detail: 'large size', kind: CompletionItemKind.Unit),
'status-xl': DaisyuiComponent(label: 'status-xl', detail: 'extra large size', kind: CompletionItemKind.Unit),
'file-input': DaisyuiComponent(label: 'file-input', detail: 'For <input type="file"> element', kind: CompletionItemKind.Constant),
'file-input-ghost': DaisyuiComponent(label: 'file-input-ghost', detail: 'ghost style', kind: CompletionItemKind.Property),
'file-input-neutral': DaisyuiComponent(label: 'file-input-neutral', detail: 'neutral color', kind: CompletionItemKind.Color),
'file-input-primary': DaisyuiComponent(label: 'file-input-primary', detail: 'primary color', kind: CompletionItemKind.Color),
'file-input-secondary': DaisyuiComponent(label: 'file-input-secondary', detail: 'secondary color', kind: CompletionItemKind.Color),
'file-input-accent': DaisyuiComponent(label: 'file-input-accent', detail: 'accent color', kind: CompletionItemKind.Color),
'file-input-info': DaisyuiComponent(label: 'file-input-info', detail: 'info color', kind: CompletionItemKind.Color),
'file-input-success': DaisyuiComponent(label: 'file-input-success', detail: 'success color', kind: CompletionItemKind.Color),
'file-input-warning': DaisyuiComponent(label: 'file-input-warning', detail: 'warning color', kind: CompletionItemKind.Color),
'file-input-error': DaisyuiComponent(label: 'file-input-error', detail: 'error color', kind: CompletionItemKind.Color),
'file-input-xs': DaisyuiComponent(label: 'file-input-xs', detail: 'Extra small size', kind: CompletionItemKind.Unit),
'file-input-sm': DaisyuiComponent(label: 'file-input-sm', detail: 'Small size', kind: CompletionItemKind.Unit),
'file-input-md': DaisyuiComponent(label: 'file-input-md', detail: 'Medium size', kind: CompletionItemKind.Unit),
'file-input-lg': DaisyuiComponent(label: 'file-input-lg', detail: 'Large size', kind: CompletionItemKind.Unit),
'file-input-xl': DaisyuiComponent(label: 'file-input-xl', detail: 'Extra large size', kind: CompletionItemKind.Unit),
'diff': DaisyuiComponent(label: 'diff', detail: 'Container element', kind: CompletionItemKind.Constant),
'diff-item-1': DaisyuiComponent(label: 'diff-item-1', detail: 'First item', kind: CompletionItemKind.Field),
'diff-item-2': DaisyuiComponent(label: 'diff-item-2', detail: 'Second item', kind: CompletionItemKind.Field),
'diff-resizer': DaisyuiComponent(label: 'diff-resizer', detail: 'The resizer control', kind: CompletionItemKind.Field),
'filter': DaisyuiComponent(label: 'filter', detail: 'For a HTML <form> or a <div> element that includes radio buttons for filtering items', kind: CompletionItemKind.Constant),
'filter-reset': DaisyuiComponent(label: 'filter-reset', detail: "An alternative to the reset button if you can't use a HTML form", kind: CompletionItemKind.Field),
'theme-controller': DaisyuiComponent(label: 'theme-controller', detail: 'For a checkbox or radio input that must change the page theme', kind: CompletionItemKind.Constant),
};
